import express from "express";
import * as adminController from "./controller.js";
import {
  authenticate,
  requireAdmin,
} from "../../middlewares/auth.middleware.js";

const router = express.Router();

router.post(
  "/get-users-by-admin",
  authenticate,
  requireAdmin,
  adminController.getUsersByAdmin,
);
router.post(
  "/update-user",
  authenticate,
  requireAdmin,
  adminController.updateUser,
);
router.post(
  "/delete-user",
  authenticate,
  requireAdmin,
  adminController.deleteUser,
);
router.post(
  "/toggle-user-status",
  authenticate,
  requireAdmin,
  adminController.toggleUserStatus,
);
router.post(
  "/toggle-user-verification",
  authenticate,
  requireAdmin,
  adminController.toggleUserVerification,
);
router.post(
  "/create-user",
  authenticate,
  requireAdmin,
  adminController.createUser,
);
router.post(
  "/get-admin-dashboard-stats",
  authenticate,
  requireAdmin,
  adminController.getAdminDashboardStats,
);
router.post(
  "/get-user-activity",
  authenticate,
  requireAdmin,
  adminController.getUserActivity,
);

// ── Subscription Tier CRUD ──────────────────────────────────────────────────
router.post(
  "/subscription-tiers/seed",
  authenticate,
  requireAdmin,
  adminController.seedSubscriptionTiers,
);
router.post(
  "/subscription-tiers/create",
  authenticate,
  requireAdmin,
  adminController.createSubscriptionTier,
);
router.post(
  "/subscription-tiers/update",
  authenticate,
  requireAdmin,
  adminController.updateSubscriptionTier,
);
router.post(
  "/subscription-tiers/delete",
  authenticate,
  requireAdmin,
  adminController.deleteSubscriptionTier,
);
router.post(
  "/subscription-tiers/list",
  authenticate,
  requireAdmin,
  adminController.listSubscriptionTiers,
);
router.post(
  "/subscription-tiers/sync-stripe",
  authenticate,
  requireAdmin,
  adminController.syncStripeTiers,
);

// ── User Subscription Management ────────────────────────────────────────────
router.post(
  "/get-subscriptions-users",
  authenticate,
  requireAdmin,
  adminController.getSubscribedUsers,
);
router.post(
  "/sync-stripe-users",
  authenticate,
  requireAdmin,
  adminController.syncStripeSubscribers,
);
router.post(
  "/subscriptions/update-user",
  authenticate,
  requireAdmin,
  adminController.updateUserSubscription,
);
router.post(
  "/subscriptions/suspend",
  authenticate,
  requireAdmin,
  adminController.suspendUserSubscription,
);
router.post(
  "/subscriptions/refund",
  authenticate,
  requireAdmin,
  adminController.refundUserSubscription,
);
router.post(
  "/get-all-activity",
  authenticate,
  requireAdmin,
  adminController.getAllActivity,
);
router.post(
  "/delete-activity",
  authenticate,
  requireAdmin,
  adminController.deleteActivity,
);
router.post(
  "/add-daily-verse",
  authenticate,
  requireAdmin,
  adminController.addDailyVerse,
);
router.post(
  "/get-all-daily-verses",
  authenticate,
  requireAdmin,
  adminController.getAllDailyVerses,
);
router.post(
  "/delete-daily-verse",
  authenticate,
  requireAdmin,
  adminController.deleteDailyVerse,
);
router.post(
  "/add-daily-devotion",
  authenticate,
  requireAdmin,
  adminController.addDailyDevotion,
);
router.post(
  "/get-all-daily-devotions",
  authenticate,
  requireAdmin,
  adminController.getAllDailyDevotions,
);
router.post(
  "/delete-daily-devotion",
  authenticate,
  requireAdmin,
  adminController.deleteDailyDevotion,
);
router.post(
  "/add-daily-exegesis",
  authenticate,
  requireAdmin,
  adminController.addDailyExegesis,
);
router.post(
  "/get-all-daily-exegesis",
  authenticate,
  requireAdmin,
  adminController.getAllDailyExegesis,
);
router.post(
  "/delete-daily-exegesis",
  authenticate,
  requireAdmin,
  adminController.deleteDailyExegesis,
);

// Site settings
router.post(
  "/get-site-setting",
  authenticate,
  requireAdmin,
  adminController.getSiteSetting,
);
router.post(
  "/set-site-setting",
  authenticate,
  requireAdmin,
  adminController.setSiteSetting,
);

export default router;
