import { PrismaClient } from "@prisma/client";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../.env") });

const prisma = new PrismaClient();

const questions = [
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — EASY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "How many days did God take to create the heavens and the earth?",
    optionsJson: JSON.stringify(["Five", "Six", "Seven", "Ten"]),
    correctAnswer: 1,
    explanation: "God created the heavens and the earth in six days and rested on the seventh day (Genesis 1).",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 31,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did God create on the fourth day?",
    optionsJson: JSON.stringify(["Trees and plants", "Fish and birds", "The sun, moon, and stars", "Land animals"]),
    correctAnswer: 2,
    explanation: "On the fourth day, God created the sun, moon, and stars to separate day from night and mark seasons (Genesis 1:14-19).",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did Adam and Eve eat that led to their expulsion from the Garden of Eden?",
    optionsJson: JSON.stringify(["Fruit from the tree of life", "Fruit from the tree of the knowledge of good and evil", "Bread from heaven", "Grapes from the vine"]),
    correctAnswer: 1,
    explanation: "Adam and Eve ate from the tree of the knowledge of good and evil, which God had commanded them not to eat (Genesis 3:6).",
    bookName: "Genesis",
    chapter: 3,
    verseNumber: 6,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who built the ark to survive the great flood?",
    optionsJson: JSON.stringify(["Abraham", "Moses", "Noah", "David"]),
    correctAnswer: 2,
    explanation: "God instructed Noah to build an ark to save his family and the animals from the flood (Genesis 6-7).",
    bookName: "Genesis",
    chapter: 6,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "How many pairs of each clean animal did God tell Noah to take on the ark?",
    optionsJson: JSON.stringify(["One pair", "Seven pairs", "One of each kind", "Four pairs"]),
    correctAnswer: 1,
    explanation: "God told Noah to take seven pairs (fourteen) of every clean animal and one pair of unclean animals (Genesis 7:2-3).",
    bookName: "Genesis",
    chapter: 7,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What sign did God give as a covenant that He would never again flood the whole earth?",
    optionsJson: JSON.stringify(["A star", "A dove", "A rainbow", "A fire"]),
    correctAnswer: 2,
    explanation: "God set the rainbow in the clouds as a sign of His covenant never to destroy the earth by flood again (Genesis 9:13-16).",
    bookName: "Genesis",
    chapter: 9,
    verseNumber: 13,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did the people build at Babel to make a name for themselves?",
    optionsJson: JSON.stringify(["A great army", "A tower", "A walled city", "A golden statue"]),
    correctAnswer: 1,
    explanation: "The people built a tower in Shinar (Babel) to reach the heavens and make a name for themselves. God confused their language (Genesis 11:1-9).",
    bookName: "Genesis",
    chapter: 11,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which patriarch was promised by God that his descendants would be as numerous as the stars?",
    optionsJson: JSON.stringify(["Moses", "David", "Abraham", "Solomon"]),
    correctAnswer: 2,
    explanation: "God brought Abraham outside and told him to count the stars, saying his descendants would be that numerous (Genesis 15:5).",
    bookName: "Genesis",
    chapter: 15,
    verseNumber: 5,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What was the name of Abraham's son born to Hagar?",
    optionsJson: JSON.stringify(["Isaac", "Jacob", "Ishmael", "Esau"]),
    correctAnswer: 2,
    explanation: "Ishmael was born to Abraham and Hagar, Sarah's maidservant (Genesis 16:15).",
    bookName: "Genesis",
    chapter: 16,
    verseNumber: 15,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "How many years did the Israelites wander in the wilderness?",
    optionsJson: JSON.stringify(["20 years", "40 years", "70 years", "10 years"]),
    correctAnswer: 1,
    explanation: "The Israelites wandered in the wilderness for 40 years because of their unbelief and refusal to enter the Promised Land (Numbers 14:33-34).",
    bookName: "Numbers",
    chapter: 14,
    verseNumber: 33,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who received the Ten Commandments on Mount Sinai?",
    optionsJson: JSON.stringify(["Aaron", "Joshua", "Moses", "Elijah"]),
    correctAnswer: 2,
    explanation: "Moses received the Ten Commandments from God on Mount Sinai (Exodus 20:1-17).",
    bookName: "Exodus",
    chapter: 20,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What was the first plague that God sent upon Egypt?",
    optionsJson: JSON.stringify(["Frogs", "Darkness", "Water turned to blood", "Boils"]),
    correctAnswer: 2,
    explanation: "The first plague was turning the Nile River and all water in Egypt into blood (Exodus 7:14-24).",
    bookName: "Exodus",
    chapter: 7,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which sea did the Israelites cross when fleeing from Egypt?",
    optionsJson: JSON.stringify(["Mediterranean Sea", "Red Sea", "Dead Sea", "Sea of Galilee"]),
    correctAnswer: 1,
    explanation: "God parted the Red Sea so the Israelites could cross on dry ground, then brought the waters back on the pursuing Egyptians (Exodus 14).",
    bookName: "Exodus",
    chapter: 14,
    verseNumber: 21,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did God provide from heaven to feed the Israelites in the wilderness?",
    optionsJson: JSON.stringify(["Bread from angels", "Manna", "Quail", "Both manna and quail"]),
    correctAnswer: 3,
    explanation: "God provided both manna (bread from heaven) and quail to feed the Israelites in the wilderness (Exodus 16).",
    bookName: "Exodus",
    chapter: 16,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who led the Israelites across the Jordan River into the Promised Land after Moses died?",
    optionsJson: JSON.stringify(["Caleb", "Joshua", "Samuel", "Elijah"]),
    correctAnswer: 1,
    explanation: "Joshua succeeded Moses and led the Israelites across the Jordan River to conquer the Promised Land (Joshua 1-3).",
    bookName: "Joshua",
    chapter: 1,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which city's walls fell down after the Israelites marched around them for seven days?",
    optionsJson: JSON.stringify(["Jerusalem", "Jericho", "Ai", "Hebron"]),
    correctAnswer: 1,
    explanation: "The walls of Jericho fell after the Israelites marched around the city once a day for six days and seven times on the seventh day (Joshua 6).",
    bookName: "Joshua",
    chapter: 6,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who defeated the giant Goliath?",
    optionsJson: JSON.stringify(["Saul", "Jonathan", "David", "Samson"]),
    correctAnswer: 2,
    explanation: "David, a young shepherd, defeated the Philistine giant Goliath with a sling and a stone (1 Samuel 17).",
    bookName: "1 Samuel",
    chapter: 17,
    verseNumber: 50,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the first king of Israel?",
    optionsJson: JSON.stringify(["David", "Saul", "Solomon", "Samuel"]),
    correctAnswer: 1,
    explanation: "Saul was the first king of Israel, anointed by the prophet Samuel (1 Samuel 10:1).",
    bookName: "1 Samuel",
    chapter: 10,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who built the first Temple in Jerusalem?",
    optionsJson: JSON.stringify(["David", "Solomon", "Hezekiah", "Zerubbabel"]),
    correctAnswer: 1,
    explanation: "King Solomon built the first Temple in Jerusalem, though his father David had prepared the materials (1 Kings 6).",
    bookName: "1 Kings",
    chapter: 6,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which prophet was taken up to heaven in a whirlwind?",
    optionsJson: JSON.stringify(["Elisha", "Elijah", "Isaiah", "Jeremiah"]),
    correctAnswer: 1,
    explanation: "Elijah was taken up to heaven in a chariot of fire by a whirlwind (2 Kings 2:11).",
    bookName: "2 Kings",
    chapter: 2,
    verseNumber: 11,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was thrown into a den of lions but was protected by God?",
    optionsJson: JSON.stringify(["Jeremiah", "Daniel", "Shadrach", "Joseph"]),
    correctAnswer: 1,
    explanation: "Daniel was thrown into a den of lions for praying to God against the king's decree, but God shut the lions' mouths (Daniel 6).",
    bookName: "Daniel",
    chapter: 6,
    verseNumber: 16,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which three young men were thrown into a fiery furnace but were not burned?",
    optionsJson: JSON.stringify(["Daniel, Hananiah, and Mishael", "Shadrach, Meshach, and Abednego", "Meshach, Daniel, and Azariah", "Hananiah, Azariah, and Michael"]),
    correctAnswer: 1,
    explanation: "Shadrach, Meshach, and Abednego were thrown into the fiery furnace for refusing to worship Nebuchadnezzar's golden image and survived (Daniel 3).",
    bookName: "Daniel",
    chapter: 3,
    verseNumber: 12,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who interpreted King Nebuchadnezzar's dream of the great statue?",
    optionsJson: JSON.stringify(["Daniel", "Isaiah", "Ezekiel", "Jeremiah"]),
    correctAnswer: 0,
    explanation: "Daniel interpreted Nebuchadnezzar's dream of the statue made of gold, silver, bronze, iron, and clay (Daniel 2).",
    bookName: "Daniel",
    chapter: 2,
    verseNumber: 31,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the strong man who lost his strength when his hair was cut?",
    optionsJson: JSON.stringify(["Gideon", "Samson", "Jephthah", "Abimelech"]),
    correctAnswer: 1,
    explanation: "Samson's supernatural strength came from his Nazirite vow. Delilah cut his hair, and he lost his strength (Judges 16:17-19).",
    bookName: "Judges",
    chapter: 16,
    verseNumber: 17,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the first woman created?",
    optionsJson: JSON.stringify(["Sarah", "Rebekah", "Eve", "Rachel"]),
    correctAnswer: 2,
    explanation: "Eve was the first woman, created by God from Adam's rib (Genesis 2:21-22).",
    bookName: "Genesis",
    chapter: 2,
    verseNumber: 22,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did Cain do to his brother Abel?",
    optionsJson: JSON.stringify(["He deceived him", "He killed him", "He stole from him", "He exiled him"]),
    correctAnswer: 1,
    explanation: "Cain killed his brother Abel out of jealousy because God accepted Abel's offering but not Cain's (Genesis 4:8).",
    bookName: "Genesis",
    chapter: 4,
    verseNumber: 8,
    category: "old-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — MEDIUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What did Jacob receive from his father Isaac by deceiving him?",
    optionsJson: JSON.stringify(["The family wealth", "The birthright blessing", "The land of Canaan", "The priesthood"]),
    correctAnswer: 1,
    explanation: "Jacob, disguised as his brother Esau, received the blessing of the firstborn from his blind father Isaac (Genesis 27).",
    bookName: "Genesis",
    chapter: 27,
    verseNumber: 27,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many plagues did God send upon Egypt before Pharaoh released the Israelites?",
    optionsJson: JSON.stringify(["7", "10", "12", "3"]),
    correctAnswer: 1,
    explanation: "God sent ten plagues upon Egypt: blood, frogs, gnats, flies, livestock disease, boils, hail, locusts, darkness, and the death of the firstborn (Exodus 7-12).",
    bookName: "Exodus",
    chapter: 7,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "What was the name of Moses' brother who served as his spokesperson?",
    optionsJson: JSON.stringify(["Aaron", "Joshua", "Caleb", "Hur"]),
    correctAnswer: 0,
    explanation: "Aaron, Moses' brother, was appointed by God to speak for Moses because Moses felt inadequate as a speaker (Exodus 4:14-16).",
    bookName: "Exodus",
    chapter: 4,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many books are in the Torah (the first five books of the Old Testament)?",
    optionsJson: JSON.stringify(["Three", "Five", "Seven", "Ten"]),
    correctAnswer: 1,
    explanation: "The Torah consists of five books: Genesis, Exodus, Leviticus, Numbers, and Deuteronomy.",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet was swallowed by a great fish?",
    optionsJson: JSON.stringify(["Elijah", "Jonah", "Daniel", "Habakkuk"]),
    correctAnswer: 1,
    explanation: "Jonah was swallowed by a great fish (whale) when he tried to flee from God's command to preach to Nineveh (Jonah 1:17).",
    bookName: "Jonah",
    chapter: 1,
    verseNumber: 17,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the mother of the prophet Samuel?",
    optionsJson: JSON.stringify(["Hannah", "Leah", "Rachel", "Miriam"]),
    correctAnswer: 0,
    explanation: "Hannah, who was barren, prayed earnestly for a son and promised to dedicate him to the Lord. God gave her Samuel (1 Samuel 1).",
    bookName: "1 Samuel",
    chapter: 1,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which king of Israel was known for his wisdom?",
    optionsJson: JSON.stringify(["David", "Saul", "Solomon", "Hezekiah"]),
    correctAnswer: 2,
    explanation: "King Solomon was renowned for his wisdom, which God granted him when he asked for wisdom rather than wealth or power (1 Kings 3).",
    bookName: "1 Kings",
    chapter: 3,
    verseNumber: 12,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What object did the Israelites carry into battle that represented God's presence?",
    optionsJson: JSON.stringify(["The bronze serpent", "The Ark of the Covenant", "The golden lampstand", "The altar of incense"]),
    correctAnswer: 1,
    explanation: "The Ark of the Covenant represented God's presence among His people and was carried before the Israelites into battle (Joshua 6:4-6).",
    bookName: "Joshua",
    chapter: 6,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many days and nights did Elijah travel to Mount Horeb after being fed by an angel?",
    optionsJson: JSON.stringify(["10 days", "40 days and 40 nights", "7 days", "3 days"]),
    correctAnswer: 1,
    explanation: "After being fed by an angel, Elijah traveled 40 days and 40 nights to Mount Horeb (Sinai) (1 Kings 19:8).",
    bookName: "1 Kings",
    chapter: 19,
    verseNumber: 8,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet wrote the book that describes a valley of dry bones coming to life?",
    optionsJson: JSON.stringify(["Isaiah", "Jeremiah", "Ezekiel", "Zechariah"]),
    correctAnswer: 2,
    explanation: "Ezekiel's vision of the valley of dry bones symbolizes the restoration of Israel (Ezekiel 37:1-14).",
    bookName: "Ezekiel",
    chapter: 37,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which book of the Bible contains the story of Ruth?",
    optionsJson: JSON.stringify(["Judges", "Ruth", "1 Samuel", "Joshua"]),
    correctAnswer: 1,
    explanation: "The book of Ruth tells the story of Ruth, a Moabite woman who became the great-grandmother of King David.",
    bookName: "Ruth",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "How many Psalms are in the book of Psalms?",
    optionsJson: JSON.stringify(["100", "150", "175", "120"]),
    correctAnswer: 1,
    explanation: "The book of Psalms contains 150 songs and prayers, many attributed to King David.",
    bookName: "Psalms",
    chapter: 150,
    verseNumber: 6,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which method did Gideon use to confirm God's promise of victory?",
    optionsJson: JSON.stringify(["Burning a sacrifice", "A fleece of wool", "A dream", "Casting lots"]),
    correctAnswer: 1,
    explanation: "Gideon placed a fleece of wool on the threshing floor and asked God to make it wet with dew while the ground remained dry, then the reverse (Judges 6:36-40).",
    bookName: "Judges",
    chapter: 6,
    verseNumber: 37,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which Persian king allowed the Jews to return and rebuild Jerusalem?",
    optionsJson: JSON.stringify(["Darius", "Cyrus", "Artaxerxes", "Xerxes"]),
    correctAnswer: 1,
    explanation: "King Cyrus of Persia issued a decree allowing the Jewish exiles to return to Jerusalem and rebuild the Temple (Ezra 1:1-4).",
    bookName: "Ezra",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Who was the prophet that confronted King David about his sin with Bathsheba?",
    optionsJson: JSON.stringify(["Nathan", "Samuel", "Gad", "Elijah"]),
    correctAnswer: 0,
    explanation: "The prophet Nathan confronted King David about his adultery with Bathsheba and the murder of Uriah using a parable (2 Samuel 12).",
    bookName: "2 Samuel",
    chapter: 12,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — HARD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "In the book of Job, what were the names of Job's three friends who came to comfort him?",
    optionsJson: JSON.stringify(["Eliphaz, Bildad, and Zophar", "Elihu, Eliphaz, and Bildad", "Eliphaz, Elihu, and Zophar", "Bildad, Zophar, and Elihu"]),
    correctAnswer: 0,
    explanation: "Job's three friends were Eliphaz the Temanite, Bildad the Shuhite, and Zophar the Naamathite. A fourth friend, Elihu, spoke later (Job 2:11, 32:2).",
    bookName: "Job",
    chapter: 2,
    verseNumber: 11,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which prophet was told to marry a prostitute as a symbol of God's relationship with Israel?",
    optionsJson: JSON.stringify(["Isaiah", "Hosea", "Ezekiel", "Amos"]),
    correctAnswer: 1,
    explanation: "Hosea was commanded by God to marry Gomer, a prostitute, as a living symbol of Israel's unfaithfulness to God (Hosea 1:2).",
    bookName: "Hosea",
    chapter: 1,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "How many chapters are in the book of Psalms attributed to the Sons of Korah?",
    optionsJson: JSON.stringify(["10", "11", "12", "7"]),
    correctAnswer: 1,
    explanation: "Eleven psalms are attributed to the Sons of Korah: Psalms 42, 44-49, 84-85, and 87-88.",
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which king of Israel had a dream of a tree that was cut down, symbolizing his temporary madness?",
    optionsJson: JSON.stringify(["Belshazzar", "Nebuchadnezzar", "Ahasuerus", "Jehoiakim"]),
    correctAnswer: 1,
    explanation: "King Nebuchadnezzar had a dream of a great tree that was cut down, which Daniel interpreted as Nebuchadnezzar's coming madness (Daniel 4).",
    bookName: "Daniel",
    chapter: 4,
    verseNumber: 10,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which minor prophet wrote the shortest book in the Old Testament?",
    optionsJson: JSON.stringify(["Nahum", "Obadiah", "Haggai", "Malachi"]),
    correctAnswer: 1,
    explanation: "The book of Obadiah is the shortest book in the Old Testament with only 21 verses.",
    bookName: "Obadiah",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "What was the name of the high priest who was also a judge over Israel?",
    optionsJson: JSON.stringify(["Aaron", "Eli", "Samuel", "Eleazar"]),
    correctAnswer: 1,
    explanation: "Eli served as both high priest and judge over Israel. He mentored the young Samuel (1 Samuel 1-4).",
    bookName: "1 Samuel",
    chapter: 1,
    verseNumber: 9,
    category: "old-testament",
    difficulty: "hard",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — EASY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "In which town was Jesus born?",
    optionsJson: JSON.stringify(["Nazareth", "Jerusalem", "Bethlehem", "Capernaum"]),
    correctAnswer: 2,
    explanation: "Jesus was born in Bethlehem of Judea, as prophesied by Micah (Micah 5:2, Matthew 2:1).",
    bookName: "Matthew",
    chapter: 2,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many apostles did Jesus choose?",
    optionsJson: JSON.stringify(["7", "10", "12", "14"]),
    correctAnswer: 2,
    explanation: "Jesus chose twelve apostles to be with Him and to be sent out to preach (Mark 3:14-19).",
    bookName: "Mark",
    chapter: 3,
    verseNumber: 14,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which disciple walked on water with Jesus?",
    optionsJson: JSON.stringify(["John", "James", "Peter", "Andrew"]),
    correctAnswer: 2,
    explanation: "Peter walked on water toward Jesus but began to sink when he doubted (Matthew 14:28-31).",
    bookName: "Matthew",
    chapter: 14,
    verseNumber: 29,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many fish did the disciples catch when Jesus performed the miraculous catch?",
    optionsJson: JSON.stringify(["153", "100", "99", "200"]),
    correctAnswer: 0,
    explanation: "The disciples caught 153 fish when Jesus directed them to cast the net on the right side (John 21:11).",
    bookName: "John",
    chapter: 21,
    verseNumber: 11,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did Jesus turn water into at the wedding in Cana?",
    optionsJson: JSON.stringify(["Milk", "Honey", "Wine", "Oil"]),
    correctAnswer: 2,
    explanation: "Jesus performed His first miracle by turning water into wine at a wedding in Cana (John 2:1-11).",
    bookName: "John",
    chapter: 2,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which parable tells the story of a son who left home and was welcomed back by his father?",
    optionsJson: JSON.stringify(["The Good Samaritan", "The Prodigal Son", "The Lost Sheep", "The Lost Coin"]),
    correctAnswer: 1,
    explanation: "The Parable of the Prodigal Son tells of a son who squandered his inheritance and was welcomed back by his forgiving father (Luke 15:11-32).",
    bookName: "Luke",
    chapter: 15,
    verseNumber: 11,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who betrayed Jesus for thirty pieces of silver?",
    optionsJson: JSON.stringify(["Peter", "Thomas", "Judas Iscariot", "Matthew"]),
    correctAnswer: 2,
    explanation: "Judas Iscariot, one of the twelve apostles, betrayed Jesus to the chief priests for thirty pieces of silver (Matthew 26:14-16).",
    bookName: "Matthew",
    chapter: 26,
    verseNumber: 15,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many days was Jesus in the tomb before His resurrection?",
    optionsJson: JSON.stringify(["Two days", "Three days", "Seven days", "Forty days"]),
    correctAnswer: 1,
    explanation: "Jesus was crucified on Friday and rose on Sunday — three days later, fulfilling His own prophecy (Matthew 12:40, 28:1-7).",
    bookName: "Matthew",
    chapter: 28,
    verseNumber: 6,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the Roman governor who condemned Jesus to crucifixion?",
    optionsJson: JSON.stringify(["Herod Antipas", "Pilate", "Caiaphas", "Felix"]),
    correctAnswer: 1,
    explanation: "Pontius Pilate, the Roman governor of Judea, condemned Jesus to crucifixion despite finding no fault in Him (John 19:4-16).",
    bookName: "John",
    chapter: 19,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which book of the New Testament describes the day of Pentecost when the Holy Spirit descended?",
    optionsJson: JSON.stringify(["Romans", "Acts", "John", "Hebrews"]),
    correctAnswer: 1,
    explanation: "The book of Acts describes the Holy Spirit descending on the apostles at Pentecost with tongues of fire (Acts 2:1-4).",
    bookName: "Acts",
    chapter: 2,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who wrote most of the letters (epistles) in the New Testament?",
    optionsJson: JSON.stringify(["Peter", "John", "Paul", "James"]),
    correctAnswer: 2,
    explanation: "The Apostle Paul wrote 13 of the 27 books of the New Testament — the most of any author.",
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many books are in the New Testament?",
    optionsJson: JSON.stringify(["21", "27", "33", "39"]),
    correctAnswer: 1,
    explanation: "The New Testament contains 27 books: 4 Gospels, Acts, 21 Epistles, and Revelation.",
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the first Christian martyr, stoned for his faith?",
    optionsJson: JSON.stringify(["Peter", "James", "Stephen", "Philip"]),
    correctAnswer: 2,
    explanation: "Stephen, one of the seven deacons, became the first Christian martyr when he was stoned (Acts 7:54-60).",
    bookName: "Acts",
    chapter: 7,
    verseNumber: 59,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did Jesus say to Satan when tempted to turn stones into bread?",
    optionsJson: JSON.stringify(["Away from me, Satan", "Man shall not live by bread alone", "Worship the Lord your God", "It is written"]),
    correctAnswer: 1,
    explanation: "Jesus quoted Deuteronomy 8:3: 'Man shall not live by bread alone, but by every word that comes from the mouth of God' (Matthew 4:4).",
    bookName: "Matthew",
    chapter: 4,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — MEDIUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which Gospel is the only one that includes the parables of the Good Samaritan and the Prodigal Son?",
    optionsJson: JSON.stringify(["Matthew", "Mark", "Luke", "John"]),
    correctAnswer: 2,
    explanation: "Only the Gospel of Luke contains the parables of the Good Samaritan (10:25-37) and the Prodigal Son (15:11-32).",
    bookName: "Luke",
    chapter: 10,
    verseNumber: 25,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "On which island was John when he received the Revelation?",
    optionsJson: JSON.stringify(["Patmos", "Cyprus", "Crete", "Malta"]),
    correctAnswer: 0,
    explanation: "John was on the island of Patmos when he received the vision that became the book of Revelation (Revelation 1:9).",
    bookName: "Revelation",
    chapter: 1,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What was Paul's name before his conversion on the road to Damascus?",
    optionsJson: JSON.stringify(["Simon", "Saul", "Silas", "Sergius"]),
    correctAnswer: 1,
    explanation: "Paul was originally called Saul, a Pharisee who persecuted Christians before his conversion (Acts 9:1-19).",
    bookName: "Acts",
    chapter: 9,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which disciple was a tax collector before following Jesus?",
    optionsJson: JSON.stringify(["Peter", "Andrew", "Matthew", "James"]),
    correctAnswer: 2,
    explanation: "Matthew (also called Levi) was a tax collector before Jesus called him to be a disciple (Matthew 9:9).",
    bookName: "Matthew",
    chapter: 9,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "How many times did Peter deny knowing Jesus before the rooster crowed?",
    optionsJson: JSON.stringify(["Two times", "Three times", "Four times", "Once"]),
    correctAnswer: 1,
    explanation: "Jesus predicted that Peter would deny Him three times before the rooster crowed, which came true (Matthew 26:69-75).",
    bookName: "Matthew",
    chapter: 26,
    verseNumber: 34,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What is the longest book in the New Testament?",
    optionsJson: JSON.stringify(["Matthew", "Luke", "Acts", "Romans"]),
    correctAnswer: 2,
    explanation: "The book of Acts is the longest book in the New Testament with 28 chapters and 1,007 verses.",
    bookName: "Acts",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which epistle contains the 'love chapter' that describes the attributes of love?",
    optionsJson: JSON.stringify(["Romans 12", "1 Corinthians 13", "Ephesians 5", "Colossians 3"]),
    correctAnswer: 1,
    explanation: "1 Corinthians 13 is known as the 'love chapter,' describing love as patient, kind, and enduring (1 Corinthians 13:4-8).",
    bookName: "1 Corinthians",
    chapter: 13,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "To whom did Jesus say 'You are Peter, and on this rock I will build My church'?",
    optionsJson: JSON.stringify(["James", "Peter", "Andrew", "John"]),
    correctAnswer: 1,
    explanation: "Jesus spoke these words to Peter after Peter confessed that Jesus is the Christ, the Son of the living God (Matthew 16:18).",
    bookName: "Matthew",
    chapter: 16,
    verseNumber: 18,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which of Paul's letters was written to a church in a city known for its temple to Artemis?",
    optionsJson: JSON.stringify(["Ephesians", "Philippians", "Colossians", "Thessalonians"]),
    correctAnswer: 0,
    explanation: "Ephesus was home to the Temple of Artemis, one of the Seven Wonders of the Ancient World. Paul wrote the letter to the Ephesians while in prison.",
    bookName: "Ephesians",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What was the name of the disciple who doubted Jesus' resurrection until he saw the wounds?",
    optionsJson: JSON.stringify(["Peter", "Thomas", "Philip", "Nathanael"]),
    correctAnswer: 1,
    explanation: "Thomas (called Didymus) said he would not believe unless he saw and touched Jesus' wounds, earning the nickname 'Doubting Thomas' (John 20:24-29).",
    bookName: "John",
    chapter: 20,
    verseNumber: 24,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many baskets of leftovers were collected after Jesus fed the 5,000?",
    optionsJson: JSON.stringify(["7", "12", "5", "3"]),
    correctAnswer: 1,
    explanation: "After feeding 5,000 men with five loaves and two fish, twelve baskets of leftovers were collected (Matthew 14:20).",
    bookName: "Matthew",
    chapter: 14,
    verseNumber: 20,
    category: "new-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — HARD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which New Testament book contains the 'Hall of Faith' chapter?",
    optionsJson: JSON.stringify(["Romans", "Galatians", "Hebrews", "James"]),
    correctAnswer: 2,
    explanation: "Hebrews 11 is the 'Hall of Faith' chapter, listing Old Testament figures who lived by faith.",
    bookName: "Hebrews",
    chapter: 11,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which king ordered the massacre of infants in Bethlehem after Jesus' birth?",
    optionsJson: JSON.stringify(["Herod the Great", "Herod Antipas", "Caesar Augustus", "Archelaus"]),
    correctAnswer: 0,
    explanation: "King Herod the Great ordered the massacre of all male infants in Bethlehem under two years old to try to kill the newborn King of the Jews (Matthew 2:16).",
    bookName: "Matthew",
    chapter: 2,
    verseNumber: 16,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which disciple was also known as 'the disciple whom Jesus loved'?",
    optionsJson: JSON.stringify(["Peter", "John", "James", "Andrew"]),
    correctAnswer: 1,
    explanation: "John is traditionally identified as 'the disciple whom Jesus loved,' a phrase used five times in the Gospel of John (John 13:23, 19:26, 20:2, 21:7, 21:20).",
    bookName: "John",
    chapter: 13,
    verseNumber: 23,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "In Revelation, how many elders are described around God's throne?",
    optionsJson: JSON.stringify(["7", "12", "24", "144"]),
    correctAnswer: 2,
    explanation: "Twenty-four elders are seated around God's throne in heaven, wearing white robes and golden crowns (Revelation 4:4).",
    bookName: "Revelation",
    chapter: 4,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which of the Gospels does NOT contain the parable of the Good Samaritan?",
    optionsJson: JSON.stringify(["Matthew", "Mark", "Luke", "All three synoptic Gospels have it"]),
    correctAnswer: 2,
    explanation: "John's Gospel does not contain the parable of the Good Samaritan. In fact, John contains no parables at all, only metaphorical language like 'I am the vine.'",
    bookName: "Luke",
    chapter: 10,
    verseNumber: 30,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "How many times does the number 'seven' appear in the book of Revelation as a symbolic number?",
    optionsJson: JSON.stringify(["14 times", "54 times", "37 times", "Over 50 times"]),
    correctAnswer: 3,
    explanation: "The number seven appears over 50 times in Revelation, including seven churches, seven seals, seven trumpets, and seven bowls.",
    bookName: "Revelation",
    chapter: 1,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which Roman centurion is mentioned for his great faith that Jesus commended?",
    optionsJson: JSON.stringify(["Cornelius", "The centurion at Capernaum", "The centurion at the cross", "Julius"]),
    correctAnswer: 1,
    explanation: "The centurion at Capernaum demonstrated great faith, telling Jesus that He only needed to speak the word for his servant to be healed (Matthew 8:5-13).",
    bookName: "Matthew",
    chapter: 8,
    verseNumber: 5,
    category: "new-testament",
    difficulty: "hard",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL BIBLE KNOWLEDGE — EASY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "How many books are in the entire Bible?",
    optionsJson: JSON.stringify(["66", "73", "39", "27"]),
    correctAnswer: 0,
    explanation: "The Bible contains 66 books: 39 in the Old Testament and 27 in the New Testament.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which language was most of the Old Testament written in?",
    optionsJson: JSON.stringify(["Aramaic", "Hebrew", "Greek", "Latin"]),
    correctAnswer: 1,
    explanation: "The Old Testament was primarily written in Hebrew, with small portions in Aramaic (Daniel 2:4-7:28, Ezra 4:8-6:18).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What language was the New Testament originally written in?",
    optionsJson: JSON.stringify(["Hebrew", "Aramaic", "Greek", "Latin"]),
    correctAnswer: 2,
    explanation: "The New Testament was written in Koine Greek, the common language of the eastern Mediterranean in the first century.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the longest book in the Bible?",
    optionsJson: JSON.stringify(["Isaiah", "Genesis", "Psalms", "Jeremiah"]),
    correctAnswer: 2,
    explanation: "The book of Psalms is the longest book in the Bible with 150 chapters (though Jeremiah has more words in the original Hebrew).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the shortest verse in the Bible?",
    optionsJson: JSON.stringify(["John 11:35", "Psalm 117:2", "1 Thessalonians 5:16", "Luke 1:38"]),
    correctAnswer: 0,
    explanation: "John 11:35 ('Jesus wept.') is the shortest verse in most English Bible translations.",
    bookName: "John",
    chapter: 11,
    verseNumber: 35,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which biblical figure is known for writing most of the Proverbs?",
    optionsJson: JSON.stringify(["David", "Solomon", "Moses", "Isaiah"]),
    correctAnswer: 1,
    explanation: "King Solomon is traditionally credited with writing most of the book of Proverbs and Ecclesiastes (Proverbs 1:1).",
    bookName: "Proverbs",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the first book of the Bible?",
    optionsJson: JSON.stringify(["Exodus", "Leviticus", "Genesis", "Job"]),
    correctAnswer: 2,
    explanation: "Genesis is the first book of the Bible, describing creation, the fall, and the patriarchs.",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the last book of the Bible?",
    optionsJson: JSON.stringify(["Jude", "Revelation", "Malachi", "John"]),
    correctAnswer: 1,
    explanation: "Revelation is the last book of the Bible, describing John's vision of the end times and the new creation.",
    bookName: "Revelation",
    chapter: 22,
    verseNumber: 21,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which mountain did Moses receive the Ten Commandments on?",
    optionsJson: JSON.stringify(["Mount Zion", "Mount Sinai", "Mount Carmel", "Mount Nebo"]),
    correctAnswer: 1,
    explanation: "Moses received the Ten Commandments from God on Mount Sinai (Exodus 19-20).",
    bookName: "Exodus",
    chapter: 19,
    verseNumber: 20,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What does the word 'Gospel' mean?",
    optionsJson: JSON.stringify(["History", "Good news", "Teaching", "Prophecy"]),
    correctAnswer: 1,
    explanation: "The word 'Gospel' comes from the Greek word 'euangelion,' meaning 'good news' — the good news of Jesus Christ.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the longest chapter in the Bible?",
    optionsJson: JSON.stringify(["Psalm 119", "Psalm 23", "Isaiah 53", "Genesis 1"]),
    correctAnswer: 0,
    explanation: "Psalm 119 is the longest chapter in the Bible with 176 verses, each focusing on the Word of God.",
    bookName: "Psalms",
    chapter: 119,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the shortest chapter in the Bible?",
    optionsJson: JSON.stringify(["Psalm 117", "Psalm 1", "John 11", "Obadiah 1"]),
    correctAnswer: 0,
    explanation: "Psalm 117 is the shortest chapter in the Bible with only two verses: 'Praise the Lord, all you nations!'",
    bookName: "Psalms",
    chapter: 117,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL BIBLE KNOWLEDGE — MEDIUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which Old Testament book does NOT mention God directly?",
    optionsJson: JSON.stringify(["Ecclesiastes", "Song of Solomon", "Esther", "Lamentations"]),
    correctAnswer: 2,
    explanation: "The book of Esther is the only book in the Bible that does not explicitly mention God.",
    bookName: "Esther",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "How many authors contributed to the writing of the Bible?",
    optionsJson: JSON.stringify(["About 40", "About 66", "About 27", "About 10"]),
    correctAnswer: 0,
    explanation: "The Bible was written by approximately 40 authors over a span of about 1,500 years, yet it tells one unified story.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Over approximately how many years was the Bible written?",
    optionsJson: JSON.stringify(["500 years", "1,000 years", "1,500 years", "2,000 years"]),
    correctAnswer: 2,
    explanation: "The Bible was written over approximately 1,500 years, from about 1400 BC to AD 90-100.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which apostle was a tentmaker by trade?",
    optionsJson: JSON.stringify(["Peter", "John", "Paul", "Barnabas"]),
    correctAnswer: 2,
    explanation: "Paul was a tentmaker by trade (Acts 18:3), which allowed him to support himself during his missionary journeys.",
    bookName: "Acts",
    chapter: 18,
    verseNumber: 3,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which prophet wrote Lamentations?",
    optionsJson: JSON.stringify(["Isaiah", "Ezekiel", "Jeremiah", "Daniel"]),
    correctAnswer: 2,
    explanation: "Jeremiah is traditionally credited as the author of Lamentations, a book mourning the destruction of Jerusalem.",
    bookName: "Lamentations",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL BIBLE KNOWLEDGE — HARD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What is the central chapter of the Bible?",
    optionsJson: JSON.stringify(["Psalm 100", "Psalm 117", "Psalm 119", "Psalm 118"]),
    correctAnswer: 3,
    explanation: "Psalm 118:8-9 are considered the central verses of the Bible. Many translations center the text at Psalm 118.",
    bookName: "Psalms",
    chapter: 118,
    verseNumber: 8,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "Which book of the Bible has the most chapters (besides Psalms)?",
    optionsJson: JSON.stringify(["Isaiah", "Jeremiah", "Ezekiel", "Genesis"]),
    correctAnswer: 1,
    explanation: "Jeremiah has 52 chapters, making it the longest prophetic book and having the most chapters after Psalms.",
    bookName: "Jeremiah",
    chapter: 52,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "How many times is the phrase 'fear not' or 'do not be afraid' used in the Bible?",
    optionsJson: JSON.stringify(["365 times", "100 times", "50 times", "200 times"]),
    correctAnswer: 0,
    explanation: "The phrase 'fear not' or 'do not be afraid' appears 365 times in the Bible — one for every day of the year.",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "In which biblical book is there no mention of sin?",
    optionsJson: JSON.stringify(["Ruth", "Esther", "Song of Solomon", "All of the above"]),
    correctAnswer: 3,
    explanation: "Ruth, Esther, and Song of Solomon are the only books of the Bible that do not mention the word 'sin.'",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "Which verse is the exact middle of the Bible?",
    optionsJson: JSON.stringify(["Psalm 118:8", "Psalm 119:1", "Psalm 100:1", "Psalm 23:1"]),
    correctAnswer: 0,
    explanation: "Psalm 118:8 ('It is better to take refuge in the Lord than to trust in man') is considered the middle verse of the Bible.",
    bookName: "Psalms",
    chapter: 118,
    verseNumber: 8,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What is the only book of the Bible that ends with a question mark?",
    optionsJson: JSON.stringify(["Jonah", "Nahum", "Malachi", "Lamentations"]),
    correctAnswer: 0,
    explanation: "The book of Jonah ends with God's question: 'Should I not have compassion on Nineveh, that great city?' (Jonah 4:11).",
    bookName: "Jonah",
    chapter: 4,
    verseNumber: 11,
    category: "general",
    difficulty: "hard",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — EASY (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Who was Abraham's wife?",
    optionsJson: JSON.stringify(["Hagar", "Sarah", "Rebekah", "Leah"]),
    correctAnswer: 1,
    explanation: "Sarah was Abraham's wife. She bore Isaac in her old age as God had promised (Genesis 21).",
    bookName: "Genesis",
    chapter: 21,
    verseNumber: 3,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which son of Abraham was almost sacrificed on Mount Moriah?",
    optionsJson: JSON.stringify(["Ishmael", "Isaac", "Jacob", "Esau"]),
    correctAnswer: 1,
    explanation: "God tested Abraham by commanding him to sacrifice Isaac on Mount Moriah, but provided a ram instead (Genesis 22).",
    bookName: "Genesis",
    chapter: 22,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did Joseph's brothers do to him out of jealousy?",
    optionsJson: JSON.stringify(["They killed him", "They sold him into slavery", "They imprisoned him", "They abandoned him in the desert"]),
    correctAnswer: 1,
    explanation: "Joseph's brothers sold him into slavery in Egypt for twenty pieces of silver (Genesis 37:28).",
    bookName: "Genesis",
    chapter: 37,
    verseNumber: 28,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who interpreted Pharaoh's dreams about seven fat cows and seven thin cows?",
    optionsJson: JSON.stringify(["Daniel", "Joseph", "Moses", "Samuel"]),
    correctAnswer: 1,
    explanation: "Joseph interpreted Pharaoh's dreams about seven years of plenty followed by seven years of famine (Genesis 41).",
    bookName: "Genesis",
    chapter: 41,
    verseNumber: 25,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What was placed in the bulrushes to hide baby Moses?",
    optionsJson: JSON.stringify(["A basket", "A wooden box", "A clay pot", "A leather bag"]),
    correctAnswer: 0,
    explanation: "Moses' mother placed him in a papyrus basket coated with tar and pitch and set it among the reeds of the Nile (Exodus 2:3).",
    bookName: "Exodus",
    chapter: 2,
    verseNumber: 3,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What was the last plague that finally convinced Pharaoh to release the Israelites?",
    optionsJson: JSON.stringify(["Death of the firstborn", "Darkness", "Locusts", "Hail"]),
    correctAnswer: 0,
    explanation: "The tenth plague — the death of the firstborn — finally broke Pharaoh's resistance (Exodus 12:29-31).",
    bookName: "Exodus",
    chapter: 12,
    verseNumber: 29,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did the Israelites eat during the Passover?",
    optionsJson: JSON.stringify(["Bread with yeast", "Unleavened bread", "Bread from heaven", "Corn"]),
    correctAnswer: 1,
    explanation: "The Israelites ate unleavened bread during the Passover, commemorating their hasty departure from Egypt (Exodus 12:8, 12:39).",
    bookName: "Exodus",
    chapter: 12,
    verseNumber: 8,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What fell from heaven to feed the Israelites in the desert?",
    optionsJson: JSON.stringify(["Bread", "Manna", "Honey", "Fish"]),
    correctAnswer: 1,
    explanation: "Manna, a bread-like substance, fell from heaven each morning to feed the Israelites during their 40 years in the wilderness (Exodus 16:31-35).",
    bookName: "Exodus",
    chapter: 16,
    verseNumber: 31,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was Moses' sister who watched over him in the bulrushes?",
    optionsJson: JSON.stringify(["Miriam", "Rachel", "Leah", "Deborah"]),
    correctAnswer: 0,
    explanation: "Miriam, Moses' sister, watched from a distance as baby Moses floated in the basket on the Nile (Exodus 2:4-8).",
    bookName: "Exodus",
    chapter: 2,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which city did Joshua conquer after the walls fell down?",
    optionsJson: JSON.stringify(["Ai", "Jericho", "Hazor", "Hebron"]),
    correctAnswer: 1,
    explanation: "The walls of Jericho fell after the Israelites marched around the city as God commanded (Joshua 6:20).",
    bookName: "Joshua",
    chapter: 6,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who anointed Saul as the first king of Israel?",
    optionsJson: JSON.stringify(["Samuel", "David", "Nathan", "Gad"]),
    correctAnswer: 0,
    explanation: "The prophet Samuel anointed Saul as the first king of Israel at God's instruction (1 Samuel 10:1).",
    bookName: "1 Samuel",
    chapter: 10,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was David's best friend?",
    optionsJson: JSON.stringify(["Jonathan", "Samuel", "Nathan", "Abner"]),
    correctAnswer: 0,
    explanation: "Jonathan, King Saul's son, was David's closest friend. Their friendship is described in 1 Samuel 18-20.",
    bookName: "1 Samuel",
    chapter: 18,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did Solomon ask God to give him?",
    optionsJson: JSON.stringify(["Riches", "Wisdom", "Long life", "Power over enemies"]),
    correctAnswer: 1,
    explanation: "Solomon asked for wisdom to govern God's people, which pleased God (1 Kings 3:9-13).",
    bookName: "1 Kings",
    chapter: 3,
    verseNumber: 9,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the queen of Persia who risked her life to save her people?",
    optionsJson: JSON.stringify(["Esther", "Vashti", "Jezebel", "Ruth"]),
    correctAnswer: 0,
    explanation: "Queen Esther risked her life by approaching King Xerxes without being summoned to save the Jewish people (Esther 4:16, 7:3).",
    bookName: "Esther",
    chapter: 4,
    verseNumber: 16,
    category: "old-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — MEDIUM (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What was the name of the servant of Abraham who found a wife for Isaac?",
    optionsJson: JSON.stringify(["Eliezer", "Laban", "Bethuel", "Ziba"]),
    correctAnswer: 0,
    explanation: "Abraham's chief servant, Eliezer, traveled to Abraham's homeland to find Rebekah as a wife for Isaac (Genesis 24).",
    bookName: "Genesis",
    chapter: 24,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many sons did Jacob have who became the twelve tribes of Israel?",
    optionsJson: JSON.stringify(["10", "12", "13", "7"]),
    correctAnswer: 1,
    explanation: "Jacob had twelve sons who became the patriarchs of the twelve tribes of Israel (Genesis 35:22-26).",
    bookName: "Genesis",
    chapter: 35,
    verseNumber: 22,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Who was Moses' wife?",
    optionsJson: JSON.stringify(["Miriam", "Zipporah", "Deborah", "Ruth"]),
    correctAnswer: 1,
    explanation: "Zipporah was the daughter of Jethro, the priest of Midian, and became Moses' wife (Exodus 2:21).",
    bookName: "Exodus",
    chapter: 2,
    verseNumber: 21,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "What was the name of the pillar that guided the Israelites by night?",
    optionsJson: JSON.stringify(["Pillar of cloud", "Pillar of fire", "Pillar of smoke", "Pillar of light"]),
    correctAnswer: 1,
    explanation: "A pillar of fire guided the Israelites by night, while a pillar of cloud guided them by day (Exodus 13:21-22).",
    bookName: "Exodus",
    chapter: 13,
    verseNumber: 21,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many spies did Moses send to scout the land of Canaan?",
    optionsJson: JSON.stringify(["2", "7", "12", "10"]),
    correctAnswer: 2,
    explanation: "Moses sent twelve spies — one from each tribe — to explore the land of Canaan (Numbers 13:1-16).",
    bookName: "Numbers",
    chapter: 13,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which two spies gave a favorable report about the Promised Land?",
    optionsJson: JSON.stringify(["Moses and Aaron", "Joshua and Caleb", "Eleazar and Ithamar", "Phinehas and Hur"]),
    correctAnswer: 1,
    explanation: "Joshua and Caleb were the only two spies who urged the people to enter the Promised Land, trusting God (Numbers 14:6-9).",
    bookName: "Numbers",
    chapter: 14,
    verseNumber: 6,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Who succeeded Moses as the leader of Israel?",
    optionsJson: JSON.stringify(["Aaron", "Joshua", "Caleb", "Eleazar"]),
    correctAnswer: 1,
    explanation: "Joshua, son of Nun, was appointed by Moses and commissioned by God to lead Israel into the Promised Land (Deuteronomy 31:7-8, Joshua 1:1-2).",
    bookName: "Deuteronomy",
    chapter: 31,
    verseNumber: 7,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which judge led Israel to victory against the Midianites with only 300 men?",
    optionsJson: JSON.stringify(["Samson", "Gideon", "Jephthah", "Barak"]),
    correctAnswer: 1,
    explanation: "Gideon led 300 men to victory against the vast Midianite army by following God's unconventional battle plan (Judges 7).",
    bookName: "Judges",
    chapter: 7,
    verseNumber: 7,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Who was the last judge of Israel before the monarchy?",
    optionsJson: JSON.stringify(["Samuel", "Eli", "Samson", "Deborah"]),
    correctAnswer: 0,
    explanation: "Samuel served as the last judge of Israel and anointed its first two kings, Saul and David (1 Samuel 1-16).",
    bookName: "1 Samuel",
    chapter: 7,
    verseNumber: 15,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "What did David use to defeat Goliath?",
    optionsJson: JSON.stringify(["A sword", "A spear", "A sling and a stone", "A bow and arrow"]),
    correctAnswer: 2,
    explanation: "David used a sling and five smooth stones to defeat the Philistine giant Goliath (1 Samuel 17:40-50).",
    bookName: "1 Samuel",
    chapter: 17,
    verseNumber: 40,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which king of Israel built an altar to foreign gods led by his wife Jezebel?",
    optionsJson: JSON.stringify(["Ahab", "Jehoshaphat", "Omri", "Jeroboam"]),
    correctAnswer: 0,
    explanation: "King Ahab, influenced by his wife Jezebel, built an altar for Baal and did more evil than any king before him (1 Kings 16:30-33).",
    bookName: "1 Kings",
    chapter: 16,
    verseNumber: 31,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet anointed Jehu as king of Israel?",
    optionsJson: JSON.stringify(["Elijah", "Elisha", "Isaiah", "Jonah"]),
    correctAnswer: 1,
    explanation: "Elisha sent a young prophet to anoint Jehu as king of Israel with a command to destroy the house of Ahab (2 Kings 9:1-10).",
    bookName: "2 Kings",
    chapter: 9,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — HARD (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What was the name of the angel who wrestled with Jacob?",
    optionsJson: JSON.stringify(["Michael", "Gabriel", "The angel of the Lord", "No name is given"]),
    correctAnswer: 3,
    explanation: "Jacob wrestled with a 'man' identified as God (Elohim). The angel/divine being did not reveal his name, but Jacob's name was changed to Israel (Genesis 32:24-30).",
    bookName: "Genesis",
    chapter: 32,
    verseNumber: 24,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "How many chapters does the book of Psalms attributed to Moses contain?",
    optionsJson: JSON.stringify(["One", "Two", "Three", "None"]),
    correctAnswer: 0,
    explanation: "Psalm 90 is the only psalm attributed to Moses, making it the oldest psalm in the Psalter.",
    bookName: "Psalms",
    chapter: 90,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which king of Judah was also a leper?",
    optionsJson: JSON.stringify(["Hezekiah", "Uzziah", "Manasseh", "Josiah"]),
    correctAnswer: 1,
    explanation: "King Uzziah was struck with leprosy when he entered the Temple to burn incense, a duty reserved for priests (2 Chronicles 26:16-21).",
    bookName: "2 Chronicles",
    chapter: 26,
    verseNumber: 19,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "What was the name of Job's youngest daughter born after his restoration?",
    optionsJson: JSON.stringify(["Jemimah", "Keziah", "Keren-Happuch", "All of the above"]),
    correctAnswer: 3,
    explanation: "After Job's restoration, he had three daughters: Jemimah, Keziah, and Keren-Happuch (Job 42:14).",
    bookName: "Job",
    chapter: 42,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which chapter in the Bible contains the Ten Commandments?",
    optionsJson: JSON.stringify(["Exodus 19", "Exodus 20", "Deuteronomy 4", "Leviticus 19"]),
    correctAnswer: 1,
    explanation: "The Ten Commandments are recorded in Exodus 20:1-17 and repeated in Deuteronomy 5:6-21.",
    bookName: "Exodus",
    chapter: 20,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "What was the name of Abraham's nephew who was rescued from Sodom?",
    optionsJson: JSON.stringify(["Lot", "Laban", "Eliezer", "Melchizedek"]),
    correctAnswer: 0,
    explanation: "Lot, Abraham's nephew, was rescued by angels before God destroyed Sodom and Gomorrah (Genesis 19).",
    bookName: "Genesis",
    chapter: 19,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which book of the Law commands that a person should love their neighbor as themselves?",
    optionsJson: JSON.stringify(["Exodus", "Leviticus", "Numbers", "Deuteronomy"]),
    correctAnswer: 1,
    explanation: "Leviticus 19:18 commands 'Love your neighbor as yourself,' which Jesus called the second greatest commandment.",
    bookName: "Leviticus",
    chapter: 19,
    verseNumber: 18,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "How many times did Naaman dip in the Jordan River to be healed of leprosy?",
    optionsJson: JSON.stringify(["Three", "Seven", "Five", "Ten"]),
    correctAnswer: 1,
    explanation: "Naaman dipped seven times in the Jordan River as Elisha instructed, and his leprosy was healed (2 Kings 5:14).",
    bookName: "2 Kings",
    chapter: 5,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — EASY (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Who baptized Jesus?",
    optionsJson: JSON.stringify(["John the Baptist", "Peter", "John the Apostle", "Andrew"]),
    correctAnswer: 0,
    explanation: "John the Baptist baptized Jesus in the Jordan River, and the heavens opened as the Spirit descended (Matthew 3:13-17).",
    bookName: "Matthew",
    chapter: 3,
    verseNumber: 13,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did Jesus say to the storm?",
    optionsJson: JSON.stringify(["Be still", "Peace, be still", "Calm down", "Silence"]),
    correctAnswer: 1,
    explanation: "Jesus rebuked the wind and said to the sea, 'Peace, be still!' and the storm immediately ceased (Mark 4:39).",
    bookName: "Mark",
    chapter: 4,
    verseNumber: 39,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which disciple was a fisherman before following Jesus?",
    optionsJson: JSON.stringify(["Matthew", "Peter", "Simon the Zealot", "Thomas"]),
    correctAnswer: 1,
    explanation: "Peter (also called Simon) was a fisherman on the Sea of Galilee when Jesus called him to be a fisher of men (Matthew 4:18-19).",
    bookName: "Matthew",
    chapter: 4,
    verseNumber: 18,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What miracle did Jesus perform at the wedding in Cana?",
    optionsJson: JSON.stringify(["Healed a sick person", "Turned water into wine", "Fed 5,000 people", "Walked on water"]),
    correctAnswer: 1,
    explanation: "Jesus performed His first public miracle by turning water into wine at a wedding in Cana of Galilee (John 2:1-11).",
    bookName: "John",
    chapter: 2,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did the soldiers place on Jesus' head during His crucifixion?",
    optionsJson: JSON.stringify(["A gold crown", "A crown of thorns", "A purple cloth", "A sign"]),
    correctAnswer: 1,
    explanation: "The Roman soldiers twisted together a crown of thorns and placed it on Jesus' head in mockery (John 19:2).",
    bookName: "John",
    chapter: 19,
    verseNumber: 2,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who helped Jesus carry His cross?",
    optionsJson: JSON.stringify(["Simon Peter", "Simon of Cyrene", "Joseph of Arimathea", "John"]),
    correctAnswer: 1,
    explanation: "Simon of Cyrene was compelled to carry Jesus' cross on the way to Golgotha (Mark 15:21).",
    bookName: "Mark",
    chapter: 15,
    verseNumber: 21,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did the angel roll away from Jesus' tomb?",
    optionsJson: JSON.stringify(["A curtain", "A stone", "A seal", "A door"]),
    correctAnswer: 1,
    explanation: "An angel of the Lord rolled away the stone from the entrance of Jesus' tomb on the morning of the resurrection (Matthew 28:2).",
    bookName: "Matthew",
    chapter: 28,
    verseNumber: 2,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who were the first people to see the resurrected Jesus?",
    optionsJson: JSON.stringify(["The apostles", "The women at the tomb", "The Pharisees", "The Roman soldiers"]),
    correctAnswer: 1,
    explanation: "Mary Magdalene and the other women who went to the tomb were the first to see the resurrected Jesus (Matthew 28:1-10, John 20:11-18).",
    bookName: "Matthew",
    chapter: 28,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How did Jesus ascend to heaven?",
    optionsJson: JSON.stringify(["In a chariot of fire", "A cloud took Him up", "He walked through a gate", "He disappeared suddenly"]),
    correctAnswer: 1,
    explanation: "Jesus was taken up into heaven as the disciples watched, and a cloud hid Him from their sight (Acts 1:9).",
    bookName: "Acts",
    chapter: 1,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What sound accompanied the arrival of the Holy Spirit at Pentecost?",
    optionsJson: JSON.stringify(["A mighty wind", "A rushing thunder", "A loud trumpet", "A gentle whisper"]),
    correctAnswer: 0,
    explanation: "The arrival of the Holy Spirit at Pentecost sounded like a mighty rushing wind (Acts 2:2).",
    bookName: "Acts",
    chapter: 2,
    verseNumber: 2,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who wrote the Gospel of Mark?",
    optionsJson: JSON.stringify(["Mark, the disciple of Peter", "Mark, the cousin of Barnabas", "John Mark", "All of the above are correct"]),
    correctAnswer: 3,
    explanation: "John Mark, also known as Mark, was a companion of Peter and Barnabas and is traditionally credited with writing the Gospel of Mark.",
    category: "new-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — MEDIUM (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What is the most quoted Old Testament book in the New Testament?",
    optionsJson: JSON.stringify(["Genesis", "Psalms", "Isaiah", "Deuteronomy"]),
    correctAnswer: 2,
    explanation: "Isaiah is the most quoted Old Testament book in the New Testament, with over 60 direct quotations.",
    bookName: "Isaiah",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which parable teaches about forgiveness and mercy through a story of a king settling debts?",
    optionsJson: JSON.stringify(["The Good Samaritan", "The Unforgiving Servant", "The Lost Sheep", "The Workers in the Vineyard"]),
    correctAnswer: 1,
    explanation: "The Parable of the Unforgiving Servant teaches that we should forgive others as God has forgiven us (Matthew 18:21-35).",
    bookName: "Matthew",
    chapter: 18,
    verseNumber: 23,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which apostle wrote letters to Timothy?",
    optionsJson: JSON.stringify(["Peter", "John", "Paul", "James"]),
    correctAnswer: 2,
    explanation: "The Apostle Paul wrote two letters to his protégé Timothy, offering guidance on church leadership and doctrine (1 Timothy, 2 Timothy).",
    bookName: "1 Timothy",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What is the 'Sermon on the Mount' and where is it found?",
    optionsJson: JSON.stringify(["A sermon by Peter in Acts 2", "Jesus' teaching in Matthew 5-7", "Paul's speech on Mars Hill", "Stephen's defense in Acts 7"]),
    correctAnswer: 1,
    explanation: "The Sermon on the Mount (Matthew 5-7) includes the Beatitudes, the Lord's Prayer, and many foundational teachings of Jesus.",
    bookName: "Matthew",
    chapter: 5,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many chapters are in the book of Acts?",
    optionsJson: JSON.stringify(["24", "28", "16", "22"]),
    correctAnswer: 1,
    explanation: "The book of Acts has 28 chapters and is the longest book in the New Testament.",
    bookName: "Acts",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What was Paul's occupation before becoming a missionary?",
    optionsJson: JSON.stringify(["Fisherman", "Tax collector", "Pharisee and tentmaker", "Doctor"]),
    correctAnswer: 2,
    explanation: "Paul was a Pharisee who studied under Gamaliel, and he also worked as a tentmaker (Acts 18:3, Philippians 3:5).",
    bookName: "Acts",
    chapter: 18,
    verseNumber: 3,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which epistle was written to a runaway slave and his master?",
    optionsJson: JSON.stringify(["Philemon", "Colossians", "Ephesians", "Titus"]),
    correctAnswer: 0,
    explanation: "Paul's letter to Philemon concerns Onesimus, a runaway slave whom Paul had converted and was sending back to his master.",
    bookName: "Philemon",
    chapter: 1,
    verseNumber: 10,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "In which city were believers first called 'Christians'?",
    optionsJson: JSON.stringify(["Jerusalem", "Antioch", "Rome", "Ephesus"]),
    correctAnswer: 1,
    explanation: "The disciples were first called Christians in Antioch of Syria (Acts 11:26).",
    bookName: "Acts",
    chapter: 11,
    verseNumber: 26,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What were the names of Paul's missionary partners who sailed with him?",
    optionsJson: JSON.stringify(["Barnabas and Mark", "Silas and Timothy", "Luke and Aquila", "All of the above at various times"]),
    correctAnswer: 3,
    explanation: "Paul traveled with various partners: Barnabas and Mark on his first journey, Silas and Timothy on his second, and Luke and Aquila at other times.",
    bookName: "Acts",
    chapter: 13,
    verseNumber: 2,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which book of the New Testament is a collection of Jesus' teachings in five major discourses?",
    optionsJson: JSON.stringify(["Mark", "Matthew", "Luke", "John"]),
    correctAnswer: 1,
    explanation: "Matthew is structured around five major discourses: the Sermon on the Mount, Missionary Discourse, Parables Discourse, Community Discourse, and Olivet Discourse.",
    bookName: "Matthew",
    chapter: 5,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — HARD (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which chapter in the New Testament contains the 'Great Commission'?",
    optionsJson: JSON.stringify(["Matthew 28", "Mark 16", "Luke 24", "Acts 1"]),
    correctAnswer: 0,
    explanation: "The Great Commission ('Go and make disciples of all nations') is found in Matthew 28:18-20.",
    bookName: "Matthew",
    chapter: 28,
    verseNumber: 18,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which epistle deals most extensively with the doctrine of justification by faith?",
    optionsJson: JSON.stringify(["Galatians", "Romans", "Ephesians", "James"]),
    correctAnswer: 1,
    explanation: "Romans provides the most extensive treatment of justification by faith, particularly in chapters 3-5 (Romans 3:28).",
    bookName: "Romans",
    chapter: 3,
    verseNumber: 28,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "How many times does the word 'faith' appear in the book of Hebrews 11?",
    optionsJson: JSON.stringify(["12", "24", "18", "32"]),
    correctAnswer: 1,
    explanation: "The word 'faith' (pistis) appears 24 times in Hebrews 11, the great 'Hall of Faith' chapter.",
    bookName: "Hebrews",
    chapter: 11,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "What was the name of the sorcerer who tried to buy the power of the Holy Spirit?",
    optionsJson: JSON.stringify(["Elymas", "Simon", "Bar-Jesus", "Both Simon and Bar-Jesus"]),
    correctAnswer: 3,
    explanation: "Simon the Sorcerer tried to buy the Holy Spirit's power with money, and was rebuked by Peter (Acts 8:9-24).",
    bookName: "Acts",
    chapter: 8,
    verseNumber: 18,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which book of the New Testament is a single chapter letter about hospitality?",
    optionsJson: JSON.stringify(["Jude", "2 John", "3 John", "Philemon"]),
    correctAnswer: 2,
    explanation: "3 John is the only book of the Bible that is a single chapter letter focused primarily on hospitality and supporting traveling missionaries.",
    bookName: "3 John",
    chapter: 1,
    verseNumber: 5,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which parable is found in all three synoptic Gospels but not in John?",
    optionsJson: JSON.stringify(["The Sower", "The Good Samaritan", "The Prodigal Son", "The Mustard Seed"]),
    correctAnswer: 3,
    explanation: "The Parable of the Mustard Seed appears in Matthew 13:31-32, Mark 4:30-32, and Luke 13:18-19. John's Gospel contains no parables.",
    bookName: "Matthew",
    chapter: 13,
    verseNumber: 31,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "What was the 'thorn in the flesh' that Paul mentions in 2 Corinthians?",
    optionsJson: JSON.stringify(["A physical illness", "A messenger of Satan", "A persecutor of Paul", "The exact nature is not specified"]),
    correctAnswer: 3,
    explanation: "Paul does not specify what his 'thorn in the flesh' was, only that it was a messenger of Satan to torment him (2 Corinthians 12:7-9).",
    bookName: "2 Corinthians",
    chapter: 12,
    verseNumber: 7,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which chapter in Revelation describes the New Jerusalem coming down from heaven?",
    optionsJson: JSON.stringify(["Revelation 21", "Revelation 22", "Revelation 20", "Revelation 19"]),
    correctAnswer: 0,
    explanation: "Revelation 21 describes John's vision of the New Jerusalem descending from heaven, with streets of gold and gates of pearl.",
    bookName: "Revelation",
    chapter: 21,
    verseNumber: 2,
    category: "new-testament",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL — EASY (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which book of the Bible is known as 'the book of beginnings'?",
    optionsJson: JSON.stringify(["Exodus", "Genesis", "John", "Acts"]),
    correctAnswer: 1,
    explanation: "Genesis is often called 'the book of beginnings' as it records the creation, the fall, and the beginning of God's covenant people.",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Who was the oldest person mentioned in the Bible?",
    optionsJson: JSON.stringify(["Noah", "Abraham", "Methuselah", "Adam"]),
    correctAnswer: 2,
    explanation: "Methuselah lived 969 years, the longest lifespan recorded in the Bible (Genesis 5:27).",
    bookName: "Genesis",
    chapter: 5,
    verseNumber: 27,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "How many days was Jonah inside the great fish?",
    optionsJson: JSON.stringify(["One day", "Three days", "Seven days", "Forty days"]),
    correctAnswer: 1,
    explanation: "Jonah was inside the great fish for three days and three nights before being vomited onto dry land (Jonah 1:17).",
    bookName: "Jonah",
    chapter: 1,
    verseNumber: 17,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the most translated book in history?",
    optionsJson: JSON.stringify(["The Quran", "The Bible", "The Torah", "The Bhagavad Gita"]),
    correctAnswer: 1,
    explanation: "The Bible is the most translated book in history, available in over 700 complete language translations.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Who wrote the book of Hebrews?",
    optionsJson: JSON.stringify(["Paul", "Luke", "Apollos", "Unknown"]),
    correctAnswer: 3,
    explanation: "The authorship of Hebrews is unknown. Various theories suggest Paul, Luke, Barnabas, or Apollos, but the book is technically anonymous.",
    bookName: "Hebrews",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "How many miracles did Jesus perform in the Gospels?",
    optionsJson: JSON.stringify(["37", "25", "50", "Over 100"]),
    correctAnswer: 0,
    explanation: "The Gospels record 37 specific miracles of Jesus, though John notes there were many others not recorded (John 21:25).",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the most frequently mentioned animal in the Bible?",
    optionsJson: JSON.stringify(["Sheep", "Lion", "Dove", "Donkey"]),
    correctAnswer: 0,
    explanation: "Sheep are mentioned over 500 times in the Bible, more than any other animal.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which book of the Bible has only one chapter?",
    optionsJson: JSON.stringify(["Jude", "Obadiah", "Philemon", "All of the above"]),
    correctAnswer: 3,
    explanation: "Obadiah (21 verses), Philemon (25 verses), 2 John (13 verses), 3 John (14 verses), and Jude (25 verses) are all single-chapter books.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the first line of the Lord's Prayer?",
    optionsJson: JSON.stringify(["Our Father who art in heaven", "Hallowed be Thy name", "Thy kingdom come", "Give us this day our daily bread"]),
    correctAnswer: 0,
    explanation: "The Lord's Prayer begins: 'Our Father in heaven, hallowed be Your name' (Matthew 6:9).",
    bookName: "Matthew",
    chapter: 6,
    verseNumber: 9,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What was Jesus' primary language?",
    optionsJson: JSON.stringify(["Hebrew", "Greek", "Aramaic", "Latin"]),
    correctAnswer: 2,
    explanation: "Jesus primarily spoke Aramaic, the common language of Judea in the first century, though He also knew Hebrew and likely Greek.",
    category: "general",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL — MEDIUM (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What is the only miracle recorded in all four Gospels?",
    optionsJson: JSON.stringify(["Walking on water", "Feeding of the 5,000", "Raising Lazarus", "Healing the blind"]),
    correctAnswer: 1,
    explanation: "The feeding of the 5,000 is the only miracle recorded in all four Gospels (Matthew 14:13-21, Mark 6:30-44, Luke 9:10-17, John 6:1-14).",
    bookName: "Matthew",
    chapter: 14,
    verseNumber: 13,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What does the word 'Messiah' mean?",
    optionsJson: JSON.stringify(["Savior", "King", "Anointed One", "Son of God"]),
    correctAnswer: 2,
    explanation: "'Messiah' comes from the Hebrew word 'Mashiach,' meaning 'Anointed One,' translated into Greek as 'Christos' (Christ).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "How many verses are there in the Bible?",
    optionsJson: JSON.stringify(["23,145", "31,102", "41,507", "18,237"]),
    correctAnswer: 1,
    explanation: "The Bible contains approximately 31,102 verses (depending on translation and versification).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which biblical woman is known for saying 'I will go where you go'?",
    optionsJson: JSON.stringify(["Esther", "Ruth", "Deborah", "Rahab"]),
    correctAnswer: 1,
    explanation: "Ruth said to Naomi: 'Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God' (Ruth 1:16).",
    bookName: "Ruth",
    chapter: 1,
    verseNumber: 16,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the Apocrypha?",
    optionsJson: JSON.stringify(["The first five books of the Bible", "A collection of deuterocanonical books", "Another name for the Gospels", "Prophecies about the end times"]),
    correctAnswer: 1,
    explanation: "The Apocrypha is a collection of Jewish books written between the Old and New Testaments, included in the Catholic canon but not in Protestant Bibles.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which book of the Bible describes God as 'slow to anger, abounding in love and faithfulness'?",
    optionsJson: JSON.stringify(["Psalms", "Exodus", "Isaiah", "Jonah"]),
    correctAnswer: 1,
    explanation: "This description of God appears first in Exodus 34:6 after Moses receives the second set of tablets on Mount Sinai.",
    bookName: "Exodus",
    chapter: 34,
    verseNumber: 6,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "How many times did Jesus appear after His resurrection according to the New Testament?",
    optionsJson: JSON.stringify(["5", "10", "12", "8"]),
    correctAnswer: 2,
    explanation: "The New Testament records 12 post-resurrection appearances of Jesus to various individuals and groups over 40 days (Acts 1:3).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the meaning of the Hebrew word 'amen'?",
    optionsJson: JSON.stringify(["Praise God", "So be it", "I believe", "Forever"]),
    correctAnswer: 1,
    explanation: "'Amen' is a Hebrew word meaning 'truly,' 'so be it,' or 'let it be so,' expressing agreement and confirmation.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which of Jesus' parables is the longest?",
    optionsJson: JSON.stringify(["The Parable of the Sower", "The Parable of the Prodigal Son", "The Parable of the Good Samaritan", "The Parable of the Vineyard Workers"]),
    correctAnswer: 1,
    explanation: "The Parable of the Prodigal Son (Luke 15:11-32) is the longest parable of Jesus, spanning 21 verses.",
    bookName: "Luke",
    chapter: 15,
    verseNumber: 11,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the 'Shema' and where is it found?",
    optionsJson: JSON.stringify(["A prayer in Psalms", "Hear, O Israel' in Deuteronomy 6:4", "The Lord's Prayer", "The Ten Commandments"]),
    correctAnswer: 1,
    explanation: "The Shema ('Hear, O Israel: The Lord our God, the Lord is one') is found in Deuteronomy 6:4 and is the central declaration of faith in Judaism.",
    bookName: "Deuteronomy",
    chapter: 6,
    verseNumber: 4,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which prophet's name means 'God is my strength'?",
    optionsJson: JSON.stringify(["Isaiah", "Ezekiel", "Daniel", "Joel"]),
    correctAnswer: 1,
    explanation: "Ezekiel means 'God strengthens' or 'God is my strength' in Hebrew.",
    bookName: "Ezekiel",
    chapter: 1,
    verseNumber: 3,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "How many words are in the longest verse of the Bible?",
    optionsJson: JSON.stringify(["Esther 8:9 has about 90 words in English", "Psalm 119:165", "John 11:35", "Jeremiah 21:4"]),
    correctAnswer: 0,
    explanation: "Esther 8:9 is the longest verse in the Bible with approximately 90 words in English (43 in the original Hebrew).",
    bookName: "Esther",
    chapter: 8,
    verseNumber: 9,
    category: "general",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL — HARD (ADDITIONAL)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which Old Testament figure is mentioned in the New Testament more than any other Old Testament figure?",
    optionsJson: JSON.stringify(["Moses", "Abraham", "David", "Elijah"]),
    correctAnswer: 1,
    explanation: "Abraham is mentioned more times in the New Testament than any other Old Testament figure, appearing in over 70 verses.",
    bookName: "Genesis",
    chapter: 12,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What percentage of the Bible is prophetic or predictive?",
    optionsJson: JSON.stringify(["About 10%", "About 27%", "About 40%", "About 5%"]),
    correctAnswer: 1,
    explanation: "Approximately 27% of the Bible (about 1 in 4 verses) contains predictive prophecy, with about 1,800 prophecies in total.",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What was the name of the slave girl who helped the spies in Jericho?",
    optionsJson: JSON.stringify(["Deborah", "Rahab", "Ruth", "Tamar"]),
    correctAnswer: 1,
    explanation: "Rahab, a prostitute in Jericho, hid the Israelite spies and helped them escape. She is listed in the genealogy of Jesus (Joshua 2, Matthew 1:5).",
    bookName: "Joshua",
    chapter: 2,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What is the longest name in the Bible?",
    optionsJson: JSON.stringify(["Maher-Shalal-Hash-Baz", "Nebuchadnezzar", "Tirhakah", "Methuselah"]),
    correctAnswer: 0,
    explanation: "Maher-Shalal-Hash-Baz (meaning 'swift is the booty, speedy is the prey') is the longest name in the Bible at 18 letters (Isaiah 8:1-3).",
    bookName: "Isaiah",
    chapter: 8,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "How many direct prophecies about Jesus are in the Old Testament?",
    optionsJson: JSON.stringify(["About 100", "Over 300", "About 50", "Over 500"]),
    correctAnswer: 1,
    explanation: "Over 300 Old Testament prophecies directly refer to Jesus Christ, many of which were fulfilled in His birth, life, death, and resurrection.",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "Which chapter in the Bible contains the most verses?",
    optionsJson: JSON.stringify(["Psalm 119", "Numbers 7", "Psalm 89", "Isaiah 1"]),
    correctAnswer: 1,
    explanation: "Numbers 7 is the longest chapter in the Bible by verse count, with 89 verses (Psalm 119 is longest by word count with 1,764 words).",
    bookName: "Numbers",
    chapter: 7,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What is the only place in the Bible where we find a description of Lucifer's fall from heaven?",
    optionsJson: JSON.stringify(["Revelation 12", "Isaiah 14", "Ezekiel 28", "Both Isaiah 14 and Ezekiel 28"]),
    correctAnswer: 3,
    explanation: "Isaiah 14:12-15 and Ezekiel 28:12-19 are the primary passages describing the fall of Lucifer/Satan, using the kings of Babylon and Tyre as types.",
    bookName: "Isaiah",
    chapter: 14,
    verseNumber: 12,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "Which book of the Bible has the greatest number of authors?",
    optionsJson: JSON.stringify(["Psalms", "Proverbs", "The Pentateuch", "The Minor Prophets"]),
    correctAnswer: 0,
    explanation: "The book of Psalms has at least seven named authors: David, Asaph, the Sons of Korah, Solomon, Moses, Heman, and Ethan.",
    bookName: "Psalms",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "How many Hebrew words are in the shortest book of the Old Testament?",
    optionsJson: JSON.stringify(["21", "291", "440", "107"]),
    correctAnswer: 1,
    explanation: "Obadiah has 21 verses and contains approximately 291 Hebrew words. In English translations it has about 440 words.",
    bookName: "Obadiah",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What is the only chapter in the Bible that begins and ends with the same word?",
    optionsJson: JSON.stringify(["Psalm 118", "Psalm 117", "Psalm 119", "Psalm 100"]),
    correctAnswer: 0,
    explanation: "Psalm 118 begins and ends with 'Oh give thanks to the Lord, for He is good; For His steadfast love endures forever!' — the same verse.",
    bookName: "Psalms",
    chapter: 118,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL — MIXED
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which book of the Bible describes the building of the Tabernacle in detail?",
    optionsJson: JSON.stringify(["Leviticus", "Numbers", "Exodus", "Deuteronomy"]),
    correctAnswer: 2,
    explanation: "Exodus 25-40 provides detailed instructions for building the Tabernacle and its furnishings.",
    bookName: "Exodus",
    chapter: 25,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Who was the Ethiopian eunuch baptized by Philip?",
    optionsJson: JSON.stringify(["A royal official of Candace", "A treasurer of the queen", "An Ethiopian court official", "Both A and B"]),
    correctAnswer: 3,
    explanation: "The Ethiopian eunuch was a court official (treasurer) of Candace, queen of the Ethiopians (Acts 8:27-39).",
    bookName: "Acts",
    chapter: 8,
    verseNumber: 27,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What did Jesus say was the greatest commandment?",
    optionsJson: JSON.stringify(["Love your neighbor", "Love the Lord your God with all your heart", "Keep the Sabbath holy", "Honor your father and mother"]),
    correctAnswer: 1,
    explanation: "Jesus said the greatest commandment is to 'Love the Lord your God with all your heart and with all your soul and with all your mind' (Matthew 22:37).",
    bookName: "Matthew",
    chapter: 22,
    verseNumber: 37,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which Old Testament prophet was known for his vision of a wheel within a wheel?",
    optionsJson: JSON.stringify(["Isaiah", "Jeremiah", "Ezekiel", "Daniel"]),
    correctAnswer: 2,
    explanation: "Ezekiel's vision of the wheel within a wheel (Ezekiel 1:15-21) is one of the most vivid prophetic visions in Scripture.",
    bookName: "Ezekiel",
    chapter: 1,
    verseNumber: 15,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "What does the name 'Immanuel' mean?",
    optionsJson: JSON.stringify(["God is great", "God with us", "God saves", "God's gift"]),
    correctAnswer: 1,
    explanation: "Immanuel (or Emmanuel) means 'God with us,' prophesied by Isaiah and fulfilled in Jesus' birth (Isaiah 7:14, Matthew 1:23).",
    bookName: "Isaiah",
    chapter: 7,
    verseNumber: 14,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "How many times did God tell Joshua to march around Jericho on the seventh day?",
    optionsJson: JSON.stringify(["Three times", "Seven times", "Ten times", "Once"]),
    correctAnswer: 1,
    explanation: "On the seventh day, the Israelites marched around Jericho seven times before the walls fell (Joshua 6:15-16).",
    bookName: "Joshua",
    chapter: 6,
    verseNumber: 15,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which apostle wrote the most books of the New Testament?",
    optionsJson: JSON.stringify(["Peter", "John", "Paul", "Matthew"]),
    correctAnswer: 2,
    explanation: "Paul wrote 13 of the 27 New Testament books: Romans, 1-2 Corinthians, Galatians, Ephesians, Philippians, Colossians, 1-2 Thessalonians, 1-2 Timothy, Titus, Philemon, and possibly Hebrews.",
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which biblical figure is described as 'a man after God's own heart'?",
    optionsJson: JSON.stringify(["Solomon", "David", "Abraham", "Moses"]),
    correctAnswer: 1,
    explanation: "David is described as 'a man after God's own heart' (1 Samuel 13:14, Acts 13:22).",
    bookName: "1 Samuel",
    chapter: 13,
    verseNumber: 14,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What was the name of the pool where the angel stirred the water for healing?",
    optionsJson: JSON.stringify(["Siloam", "Bethesda", "Gihon", "Kidron"]),
    correctAnswer: 1,
    explanation: "The Pool of Bethesda had healing powers when an angel stirred its waters. Jesus healed a man there who had been sick for 38 years (John 5:1-9).",
    bookName: "John",
    chapter: 5,
    verseNumber: 2,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which book of the Bible contains the 'Great White Throne Judgment'?",
    optionsJson: JSON.stringify(["Daniel", "Matthew", "Revelation", "Isaiah"]),
    correctAnswer: 2,
    explanation: "The Great White Throne Judgment is described in Revelation 20:11-15, where the dead are judged according to their deeds.",
    bookName: "Revelation",
    chapter: 20,
    verseNumber: 11,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Who was the Roman centurion who took charge of Paul's journey to Rome?",
    optionsJson: JSON.stringify(["Julius", "Claudius", "Cornelius", "Felix"]),
    correctAnswer: 0,
    explanation: "Julius, a centurion of the Augustan Cohort, was responsible for transporting Paul from Caesarea to Rome (Acts 27:1).",
    bookName: "Acts",
    chapter: 27,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "What is the 'Day of Atonement' called in Hebrew?",
    optionsJson: JSON.stringify(["Yom Kippur", "Rosh Hashanah", "Passover", "Sukkot"]),
    correctAnswer: 0,
    explanation: "Yom Kippur, the Day of Atonement, was the most sacred day in the Jewish calendar when the High Priest entered the Holy of Holies (Leviticus 16, 23:27).",
    bookName: "Leviticus",
    chapter: 23,
    verseNumber: 27,
    category: "old-testament",
    difficulty: "medium",
  },
];

const main = async () => {
  console.log("Seeding Bible trivia questions...");

  let created = 0;
  let skipped = 0;

  for (const q of questions) {
    try {
      // Build a unique identifier from the question text
      const questionHash = q.question.slice(0, 80);

      const existing = await prisma.triviaQuestion.findFirst({
        where: { question: { startsWith: questionHash } },
      });

      if (existing) {
        console.log(`  ~ Already exists: "${q.question.slice(0, 50)}..."`);
        skipped++;
        continue;
      }

      await prisma.triviaQuestion.create({
        data: {
          question: q.question,
          optionsJson: q.optionsJson,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation || null,
          bookName: q.bookName || null,
          chapter: q.chapter ? BigInt(q.chapter) : null,
          verseNumber: q.verseNumber ? BigInt(q.verseNumber) : null,
          category: q.category || "general",
          difficulty: q.difficulty || "medium",
          isActive: true,
          createdBy: "seed",
        },
      });
      created++;
      console.log(`  ✓ [${q.category}] ${q.question.slice(0, 60)}...`);
    } catch (error) {
      console.error(`  ✗ Error: ${error.message}`);
    }
  }

  console.log(`\nSeeded ${created} new trivia questions (${skipped} skipped, ${questions.length - created - skipped} failed).`);
  console.log(`Total questions in DB: ${await prisma.triviaQuestion.count()}`);
};

main()
  .catch((e) => {
    console.error("Error seeding trivia:", e.message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
