/**
 * Seed script for Strong's Concordance dictionary.
 *
 * Usage: node prisma/seed-strongs.js
 *
 * This seeds a comprehensive sample of Strong's entries
 * (Greek NT and Hebrew OT) and word-level verse mappings.
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const p = (s) => s;

const STRONGS_ENTRIES = [
  // ── EXISTING ENTRIES ───────────────────────────────────────
  { strongsId: 'G3056', originalWord: 'λόγος', transliteration: 'logos', pronunciation: p("log'-os"), shortDefinition: 'word, speech, message', fullDefinition: p("A word, speech, divine utterance, account, reason, or message. In John 1:1, refers to Jesus Christ as the eternal Word of God."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 330, crossReferences: 'John 1:1, John 1:14, 1 John 1:1' },
  { strongsId: 'G0025', originalWord: 'ἀγαπάω', transliteration: 'agapao', pronunciation: p("ag-ap-ah'-o"), shortDefinition: 'to love, to cherish', fullDefinition: p("To love unconditionally, to have a deep, self-sacrificing love for. Used of God's love for humanity and the love believers are to have for God and one another."), language: 'greek', partOfSpeech: 'verb', usageCount: 143 },
  { strongsId: 'G0026', originalWord: 'ἀγάπη', transliteration: 'agape', pronunciation: p("ag-ah'-pay"), shortDefinition: 'love, unconditional love', fullDefinition: p("Unconditional, self-sacrificing love. The highest form of love, used to describe God's nature and the love He commands believers to show."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 116 },
  { strongsId: 'G2889', originalWord: 'κόσμος', transliteration: 'kosmos', pronunciation: p("kos'-mos"), shortDefinition: 'world, universe, earth', fullDefinition: p("The world, the universe, the earth; by extension, the world system opposed to God; humanity in general."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'accusative', gender: 'masculine', number: 'singular', usageCount: 186 },
  { strongsId: 'G4102', originalWord: 'πίστις', transliteration: 'pistis', pronunciation: p("pis'-tis"), shortDefinition: 'faith, belief, trust', fullDefinition: p("Faith, trust, confidence in God; belief in the truths of the gospel; faithfulness, reliability."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 244 },
  { strongsId: 'G4100', originalWord: 'πιστεύω', transliteration: 'pisteuo', pronunciation: p("pist-yoo'-o"), shortDefinition: 'to believe, to trust', fullDefinition: p("To believe, to trust in, to have faith in. Used extensively in John's Gospel for saving faith in Jesus Christ."), language: 'greek', partOfSpeech: 'verb', usageCount: 248 },
  { strongsId: 'G5547', originalWord: 'Χριστός', transliteration: 'Christos', pronunciation: 'khris-tos', shortDefinition: 'Christ, Anointed One, Messiah', fullDefinition: p("The Anointed One, the Messiah, the Christ. The Greek translation of the Hebrew Messiah. Used as a title for Jesus of Nazareth."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 529 },
  { strongsId: 'G2962', originalWord: 'κύριος', transliteration: 'kurios', pronunciation: p("koo'-ree-os"), shortDefinition: 'Lord, master, sir', fullDefinition: p("Lord, master, owner. Used of God as the Supreme Being and of Jesus Christ as the divine Lord and Master."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 717 },
  { strongsId: 'G2316', originalWord: 'θεός', transliteration: 'theos', pronunciation: p("theh'-os"), shortDefinition: 'God, a god', fullDefinition: p("God, the Supreme Being; by extension, a deity, god or goddess. In the NT, primarily used for the one true God."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 1317 },
  { strongsId: 'G0036', originalWord: 'ἀγενεαλόγητος', transliteration: 'agenealogetos', pronunciation: p("ag-en-eh-al-og'-ay-tos"), shortDefinition: 'without genealogy', fullDefinition: p("Without genealogy, of unrecorded descent."), language: 'greek', partOfSpeech: 'adjective', usageCount: 1 },
  { strongsId: 'G0124', originalWord: 'Αἰγύπτιος', transliteration: 'Aiguptios', pronunciation: p("ahee-goop'-tee-os"), shortDefinition: 'Egyptian', fullDefinition: p("Egyptian, belonging to Egypt."), language: 'greek', partOfSpeech: 'adjective', usageCount: 5 },
  { strongsId: 'G0143', originalWord: 'αἰσθάνομαι', transliteration: 'aisthanomai', pronunciation: p("ahee-sthan'-om-ahee"), shortDefinition: 'to perceive, to understand', fullDefinition: p("To perceive, to understand, to discern. To grasp with the mind or senses."), language: 'greek', partOfSpeech: 'verb', usageCount: 1 },
  { strongsId: 'H7225', originalWord: 'רֵאשִׁית', transliteration: 'reshith', pronunciation: 'ray-sheeth', shortDefinition: 'beginning, first, chief', fullDefinition: p("Beginning, first, firstfruits, chief, choice part. Refers to the first or best portion of something."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 51 },
  { strongsId: 'H0430', originalWord: 'אֱלֹהִים', transliteration: 'elohim', pronunciation: 'el-o-heem', shortDefinition: 'God, gods, judges', fullDefinition: p("God, gods, judges, divine ones. The plural form used for the one true God in the Hebrew Bible, indicating majesty and fullness."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', usageCount: 2602 },
  { strongsId: 'H1254', originalWord: 'בָּרָא', transliteration: 'bara', pronunciation: 'baw-raw', shortDefinition: 'to create, to make', fullDefinition: p("To create, to shape, to make. Used exclusively for divine creation producing something new and bringing it into existence."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 54 },
  { strongsId: 'H0804', originalWord: 'שָׁמַיִם', transliteration: 'shamayim', pronunciation: p("shaw-mah'-yim"), shortDefinition: 'heaven, heavens, sky', fullDefinition: p("Heaven, heavens, sky, the visible heavens. The abode of God and the celestial realm."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'plural', usageCount: 421 },
  { strongsId: 'H0776', originalWord: 'אֶרֶץ', transliteration: 'erets', pronunciation: p("eh'-rets"), shortDefinition: 'earth, land, ground', fullDefinition: p("Earth, land, ground, country. The dry ground as distinct from the heavens and the seas."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 2504 },
  { strongsId: 'G0157', originalWord: 'αἰτία', transliteration: 'aitia', pronunciation: p("ahee-tee'-ah"), shortDefinition: 'cause, accusation, fault', fullDefinition: p("Cause, reason, ground; accusation, charge, fault."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 20 },
  { strongsId: 'G0209', originalWord: 'ἀκωλύτως', transliteration: 'akolutos', pronunciation: p("ak-o-loo'-tos"), shortDefinition: 'without hindrance, freely', fullDefinition: p("Without hindrance, freely, unhinderedly."), language: 'greek', partOfSpeech: 'adverb', usageCount: 1 },
  { strongsId: 'G0686', originalWord: 'ἄρα', transliteration: 'ara', pronunciation: p("ar'-ah"), shortDefinition: 'therefore, so, then', fullDefinition: p("Therefore, so, then, consequently. A particle expressing inference or conclusion."), language: 'greek', partOfSpeech: 'conjunction', usageCount: 49 },
  { strongsId: 'H1961', originalWord: 'הָיָה', transliteration: 'hayah', pronunciation: 'haw-yaw', shortDefinition: 'to be, become, come to pass', fullDefinition: p("To be, to exist, to happen, to become. One of the most common Hebrew verbs, used for existence, occurrence, and divine action."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 3560 },
  { strongsId: 'H8414', originalWord: 'תֹהוּ', transliteration: 'tohu', pronunciation: p("to'-hoo"), shortDefinition: 'formlessness, emptiness, chaos', fullDefinition: p("Formlessness, emptiness, chaos, wasteness. Used to describe the earth before creation and things that are worthless or vain."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', usageCount: 20 },
  { strongsId: 'H0922', originalWord: 'בֹּהוּ', transliteration: 'bohu', pronunciation: p("bo'-hoo"), shortDefinition: 'emptiness, void, waste', fullDefinition: p("Emptiness, void, waste. Used only in combination with tohu to describe the unformed state of the earth."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', usageCount: 3 },
  { strongsId: 'G1063', originalWord: 'γάρ', transliteration: 'gar', pronunciation: 'gar', shortDefinition: 'for, because, indeed', fullDefinition: p("For, because, since, indeed, then. A causal conjunction used to introduce a reason or explanation."), language: 'greek', partOfSpeech: 'conjunction', usageCount: 1041 },
  { strongsId: 'G3779', originalWord: 'οὕτως', transliteration: 'houtos', pronunciation: p("hoo'-toce"), shortDefinition: 'so, thus, in this way', fullDefinition: p("So, thus, in this way, in like manner. An adverb of manner pointing to the way something is done."), language: 'greek', partOfSpeech: 'adverb', usageCount: 208 },
  { strongsId: 'G3754', originalWord: 'ὅτι', transliteration: 'hoti', pronunciation: p("hot'-ee"), shortDefinition: 'that, because, since', fullDefinition: p("That, because, since, for. A conjunction used to introduce indirect discourse or give a reason."), language: 'greek', partOfSpeech: 'conjunction', usageCount: 1296 },
  { strongsId: 'G0846', originalWord: 'αὐτός', transliteration: 'autos', pronunciation: p("ow-tos'"), shortDefinition: 'he, himself, same', fullDefinition: p("He, himself, herself, itself, the same. A personal pronoun used for emphasis or reference."), language: 'greek', partOfSpeech: 'pronoun', gender: 'masculine', number: 'singular', usageCount: 5597 },
  { strongsId: 'G1325', originalWord: 'δίδωμι', transliteration: 'didomi', pronunciation: p("did'-o-mee"), shortDefinition: 'to give, to grant', fullDefinition: p("To give, to grant, to bestow, to supply. Used of God giving His Son and of believers giving to others."), language: 'greek', partOfSpeech: 'verb', usageCount: 415 },
  { strongsId: 'G1520', originalWord: 'εἷς', transliteration: 'heis', pronunciation: 'hice', shortDefinition: 'one, a certain, single', fullDefinition: p("One, a certain, single, only one. The cardinal number one, used both numerically and metaphorically for unity."), language: 'greek', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', usageCount: 343 },
  { strongsId: 'G3439', originalWord: 'μονογενής', transliteration: 'monogenes', pronunciation: p("mon-og-en-ace'"), shortDefinition: 'only begotten, unique, one of a kind', fullDefinition: p("Only begotten, unique, one of a kind. Used of Jesus as the unique Son of God."), language: 'greek', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', usageCount: 9, crossReferences: 'John 1:14, John 1:18, John 3:16' },
  { strongsId: 'G5207', originalWord: 'υἱός', transliteration: 'huios', pronunciation: p("hwee-os'"), shortDefinition: 'son, offspring, descendant', fullDefinition: p("Son, offspring, descendant, child. Used literally for male children and metaphorically for relationship with God."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'accusative', gender: 'masculine', number: 'singular', usageCount: 377 },
  { strongsId: 'G3956', originalWord: 'πᾶς', transliteration: 'pas', pronunciation: 'pas', shortDefinition: 'all, every, everyone, the whole', fullDefinition: p("All, every, everyone, the whole, everything. Used to indicate totality or universality."), language: 'greek', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', usageCount: 1243 },
  { strongsId: 'G1722', originalWord: 'ἐν', transliteration: 'en', pronunciation: 'en', shortDefinition: 'in, on, among, by', fullDefinition: p("In, on, among, by, with. A primary preposition denoting position or instrumentality."), language: 'greek', partOfSpeech: 'preposition', usageCount: 2752 },
  { strongsId: 'G3361', originalWord: 'μή', transliteration: 'me', pronunciation: 'may', shortDefinition: 'not, lest, that not', fullDefinition: p("Not, lest, that not. A primary particle of negation used with non-indicative moods."), language: 'greek', partOfSpeech: 'particle', usageCount: 1042 },
  { strongsId: 'G0622', originalWord: 'ἀπόλλυμι', transliteration: 'apollumi', pronunciation: p("ap-ol'-loo-mee"), shortDefinition: 'to destroy, to perish, to lose', fullDefinition: p("To destroy, to perish, to lose, to die. Used both of physical destruction and eternal perdition."), language: 'greek', partOfSpeech: 'verb', usageCount: 90 },
  { strongsId: 'G0235', originalWord: 'ἀλλά', transliteration: 'alla', pronunciation: p("al-lah'"), shortDefinition: 'but, rather, on the contrary', fullDefinition: p("But, rather, on the contrary, nevertheless. A strong adversative conjunction."), language: 'greek', partOfSpeech: 'conjunction', usageCount: 638 },
  { strongsId: 'G2192', originalWord: 'ἔχω', transliteration: 'echo', pronunciation: p("ekh'-o"), shortDefinition: 'to have, to hold, to possess', fullDefinition: p("To have, to hold, to possess, to own. Used both literally and figuratively."), language: 'greek', partOfSpeech: 'verb', usageCount: 708 },
  { strongsId: 'G0166', originalWord: 'αἰώνιος', transliteration: 'aionios', pronunciation: p("ahee-o'-nee-os"), shortDefinition: 'eternal, everlasting, unending', fullDefinition: p("Eternal, everlasting, unending, without beginning or end. Used of God's nature and the life He gives."), language: 'greek', partOfSpeech: 'adjective', gender: 'feminine', number: 'singular', usageCount: 71 },
  { strongsId: 'G2222', originalWord: 'ζωή', transliteration: 'zoe', pronunciation: p("dzo-ay'"), shortDefinition: 'life, living, existence', fullDefinition: p("Life, living, existence. Used of physical life and especially of eternal spiritual life in Christ."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'accusative', gender: 'feminine', number: 'singular', usageCount: 135, crossReferences: 'John 1:4, John 3:16, John 14:6' },
  // ── NEW GREEK ENTRIES (20+) ────────────────────────────────
  { strongsId: 'G0016', originalWord: 'ἀγαθωσύνη', transliteration: 'agathosyne', pronunciation: p("ag-ath-o-soo'-nay"), shortDefinition: 'goodness, uprightness, virtue', fullDefinition: p("Goodness, uprightness, moral excellence. Refers to the inherent goodness of God and the virtuous character He cultivates in believers. Used in the context of the fruit of the Spirit."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 4 },
  { strongsId: 'G0020', originalWord: 'ἀγαλλίασις', transliteration: 'agalliasis', pronunciation: p("ag-al-lee'-as-is"), shortDefinition: 'exceeding joy, exultation', fullDefinition: p("Exceeding joy, exultation, exuberant gladness. Expresses an intense joy often associated with worship and celebration of God's salvation."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 5 },
  { strongsId: 'G0043', originalWord: 'ἀγκάλη', transliteration: 'ankale', pronunciation: p("ang-kal'-ay"), shortDefinition: 'arm, bent arm, embrace', fullDefinition: p("A bent arm, the crook of the arm. Used in Luke 2:28 of Simeon taking the infant Jesus into his arms."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'accusative', gender: 'feminine', number: 'plural', usageCount: 1 },
  { strongsId: 'G0134', originalWord: 'αἰνέω', transliteration: 'aineo', pronunciation: p("ahee-neh'-o"), shortDefinition: 'to praise, to extol', fullDefinition: p("To praise, to extol, to speak in praise of God. Used primarily of offering praise in worship and thanksgiving."), language: 'greek', partOfSpeech: 'verb', usageCount: 9 },
  { strongsId: 'G0136', originalWord: 'αἶνος', transliteration: 'ainos', pronunciation: p("ahee'-nos"), shortDefinition: 'praise, a saying of praise', fullDefinition: p("Praise, a saying or recitation of praise. Used of praise offered to God, particularly in the triumphal entry."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 2 },
  { strongsId: 'G0142', originalWord: 'αἴρω', transliteration: 'airo', pronunciation: p("ahee'-ro"), shortDefinition: 'to take up, lift, take away', fullDefinition: p("To take up, to lift, to raise, to take away. Central in John 1:29 of Christ taking away the sin of the world."), language: 'greek', partOfSpeech: 'verb', usageCount: 101 },
  { strongsId: 'G0151', originalWord: 'αἰσχύνη', transliteration: 'aischyne', pronunciation: p("ahee-skhoo'-nay"), shortDefinition: 'shame, disgrace, dishonor', fullDefinition: p("Shame, disgrace, dishonor. Refers to the feeling of humiliation or the state of being put to shame."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 6 },
  { strongsId: 'G0156', originalWord: 'αἰτία', transliteration: 'aitia', pronunciation: p("ahee-tee'-ah"), shortDefinition: 'cause, reason, accusation', fullDefinition: p("Cause, reason, ground; accusation, charge, fault. Used of the logical basis for something and of legal accusations."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 20 },
  { strongsId: 'G0259', originalWord: 'ἅλωσις', transliteration: 'halosis', pronunciation: p("hal'-o-sis"), shortDefinition: 'capture, being taken', fullDefinition: p("Capture, the act of being taken or caught."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 1 },
  { strongsId: 'G0319', originalWord: 'ἀναγινώσκω', transliteration: 'anaginosko', pronunciation: p("an-ag-in-o'-sko"), shortDefinition: 'to read, to read aloud', fullDefinition: p("To read, to read aloud, to recognize written characters. Used of reading Scripture both publicly and privately."), language: 'greek', partOfSpeech: 'verb', usageCount: 33 },
  { strongsId: 'G0856', originalWord: 'ἀφεδρών', transliteration: 'aphedron', pronunciation: p("af-ed-rone'"), shortDefinition: 'drain, latrine, sewer', fullDefinition: p("A drain, latrine, privy. Used in Jesus' teaching that food passes through the digestive system and is eliminated."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 2 },
  { strongsId: 'G0932', originalWord: 'βασιλεία', transliteration: 'basileia', pronunciation: p("bas-il-i'-ah"), shortDefinition: 'kingdom, reign, royal power', fullDefinition: p("Kingdom, reign, sovereignty, royal power. Central to Jesus' preaching of the kingdom of God and the kingdom of heaven."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 162, crossReferences: 'Matthew 6:33, Mark 1:15, Romans 14:17' },
  { strongsId: 'G0935', originalWord: 'βασιλεύς', transliteration: 'basileus', pronunciation: p("bas-il-yooce'"), shortDefinition: 'king, ruler, sovereign', fullDefinition: p("King, ruler, sovereign. Used of earthly rulers and supremely of God and Christ as King of kings."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 117, crossReferences: '1 Timothy 1:17, Revelation 19:16' },
  { strongsId: 'G0979', originalWord: 'βίος', transliteration: 'bios', pronunciation: p("bee'-os"), shortDefinition: 'life, living, livelihood', fullDefinition: p("Life, living, means of living, livelihood. Refers to physical life and material resources in contrast to spiritual life (zoe)."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 11 },
  { strongsId: 'G0990', originalWord: 'βλέπω', transliteration: 'blepo', pronunciation: p("blep'-o"), shortDefinition: 'to see, to look, to perceive', fullDefinition: p("To see, to look, to perceive, to discern. Used of physical sight and spiritual perception."), language: 'greek', partOfSpeech: 'verb', usageCount: 135 },
  { strongsId: 'G1121', originalWord: 'γραφή', transliteration: 'graphe', pronunciation: p("graf-ay'"), shortDefinition: 'writing, scripture', fullDefinition: p("Writing, scripture, sacred writing. Used almost exclusively for the Hebrew Scriptures, emphasizing their divine authority."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 51, crossReferences: '2 Timothy 3:16, 2 Peter 1:20' },
  { strongsId: 'G1343', originalWord: 'δικαιοσύνη', transliteration: 'dikaiosyne', pronunciation: p("dik-ah-yos-oo'-nay"), shortDefinition: 'righteousness, justice, justification', fullDefinition: p("Righteousness, justice, the state of being morally right. A central theological term referring to right standing with God through faith."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 92, crossReferences: 'Romans 3:22, Romans 4:5, 2 Corinthians 5:21' },
  { strongsId: 'G1654', originalWord: 'ἐλεημοσύνη', transliteration: 'eleemosyne', pronunciation: p("el-eh-ay-mos-oo'-nay"), shortDefinition: 'mercy, pity, alms', fullDefinition: p("Mercy, pity, charitable giving, almsgiving. Refers to showing compassion through material assistance to the needy."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 13 },
  { strongsId: 'G1680', originalWord: 'ἐλπίς', transliteration: 'elpis', pronunciation: p("el-pece'"), shortDefinition: 'hope, expectation, trust', fullDefinition: p("Hope, confident expectation, trust. Not a mere wish but a settled expectation of future good based on God's promises."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 54, crossReferences: 'Romans 8:24, Hebrews 6:19, 1 Peter 1:3' },
  { strongsId: 'G1849', originalWord: 'ἐξουσία', transliteration: 'exousia', pronunciation: p("ex-oo-see'-ah"), shortDefinition: 'authority, power, right, jurisdiction', fullDefinition: p("Authority, delegated power, right, jurisdiction. Refers to legitimate power to act, command, or exercise rule."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 103 },
  { strongsId: 'G2033', originalWord: 'ἑπτά', transliteration: 'hepta', pronunciation: p("hep-tah'"), shortDefinition: 'seven', fullDefinition: p("Seven. Used literally and symbolically for completeness and perfection, prominently in Revelation."), language: 'greek', partOfSpeech: 'noun', usageCount: 88 },
  { strongsId: 'G2256', originalWord: 'ἡμίωρον', transliteration: 'hemiorion', pronunciation: p("hay-mee'-o-ron"), shortDefinition: 'half an hour', fullDefinition: p("Half an hour. Used in Revelation 8:1 of the silence in heaven before the seven trumpets."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'accusative', gender: 'masculine', number: 'singular', usageCount: 1 },
  { strongsId: 'G2398', originalWord: 'ἴδιος', transliteration: 'idios', pronunciation: p("id'-ee-os"), shortDefinition: "one's own, private, personal", fullDefinition: p("One's own, private, personal. Emphasizes personal possession, relationship, or belonging."), language: 'greek', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', usageCount: 114 },
  { strongsId: 'G2433', originalWord: 'ἱλάσκομαι', transliteration: 'hilaskomai', pronunciation: p("hil-as'-kom-ahee"), shortDefinition: 'to propitiate, to atone', fullDefinition: p("To propitiate, to make atonement for, to be merciful. Used of turning away wrath through atoning sacrifice."), language: 'greek', partOfSpeech: 'verb', usageCount: 2 },
  { strongsId: 'G2434', originalWord: 'ἱλασμός', transliteration: 'hilasmos', pronunciation: p("hil-as-mos'"), shortDefinition: 'propitiation, atonement, expiation', fullDefinition: p("Propitiation, atoning sacrifice. Refers to Christ's sacrifice that satisfies God's wrath and restores fellowship."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 2, crossReferences: '1 John 2:2, 1 John 4:10' },
  { strongsId: 'G2648', originalWord: 'κατά', transliteration: 'kata', pronunciation: p("kat-ah'"), shortDefinition: 'according to, against, down, throughout', fullDefinition: p("According to, against, down from, throughout. A versatile preposition indicating direction, opposition, or standard."), language: 'greek', partOfSpeech: 'preposition', usageCount: 473 },
  { strongsId: 'G2819', originalWord: 'κλῆρος', transliteration: 'kleros', pronunciation: p("klay'-ros"), shortDefinition: 'lot, inheritance, portion', fullDefinition: p("Lot, inheritance, allotted portion. Used of casting lots for decisions and of the believer's inheritance in Christ."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 14 },
  { strongsId: 'G2822', originalWord: 'κλητός', transliteration: 'kletos', pronunciation: p("klay-tos'"), shortDefinition: 'called, invited, appointed', fullDefinition: p("Called, invited, summoned. Used of those who are called by God to salvation and to be saints."), language: 'greek', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', usageCount: 11 },
  { strongsId: 'G3004', originalWord: 'λέγω', transliteration: 'lego', pronunciation: p("leg'-o"), shortDefinition: 'to say, to speak, to tell', fullDefinition: p("To say, to speak, to tell, to declare. One of the most common Greek verbs for verbal communication, used thousands of times."), language: 'greek', partOfSpeech: 'verb', usageCount: 2350 },
  { strongsId: 'G3173', originalWord: 'μέγας', transliteration: 'megas', pronunciation: p("meg'-as"), shortDefinition: 'great, large, mighty', fullDefinition: p("Great, large, mighty, important. Used of physical size, intensity, and metaphorical greatness."), language: 'greek', partOfSpeech: 'adjective', gender: 'masculine', number: 'singular', usageCount: 242 },
  { strongsId: 'G3440', originalWord: 'μόνον', transliteration: 'monon', pronunciation: p("mon'-on"), shortDefinition: 'only, alone, merely', fullDefinition: p("Only, alone, merely, exclusively. An adverb used to limit or restrict the scope of a statement."), language: 'greek', partOfSpeech: 'adverb', usageCount: 67 },
  { strongsId: 'G3793', originalWord: 'ὄχλος', transliteration: 'ochlos', pronunciation: p("okh'-los"), shortDefinition: 'crowd, multitude, throng', fullDefinition: p("Crowd, multitude, throng of people. Used frequently in the Gospels of the crowds that followed Jesus."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 174 },
  { strongsId: 'G3819', originalWord: 'πάλαι', transliteration: 'palai', pronunciation: p("pal'-ahee"), shortDefinition: 'long ago, formerly, of old', fullDefinition: p("Long ago, formerly, in time past. Used to refer to events that happened in the distant past."), language: 'greek', partOfSpeech: 'adverb', usageCount: 7 },
  { strongsId: 'G3856', originalWord: 'παραδειγματίζω', transliteration: 'paradeigmatizo', pronunciation: p("par-ad-ig-mat-id'-zo"), shortDefinition: 'to expose, to make an example of', fullDefinition: p("To expose publicly, to make an example of, to hold up to disgrace. Used of open shame and public display."), language: 'greek', partOfSpeech: 'verb', usageCount: 1 },
  { strongsId: 'G4060', originalWord: 'περιτίθημι', transliteration: 'peritithemi', pronunciation: p("per-ee-tith'-ay-mee"), shortDefinition: 'to place around, to put on', fullDefinition: p("To place around, to put on, to bestow, to clothe. Used of putting garments on someone and of bestowing honor."), language: 'greek', partOfSpeech: 'verb', usageCount: 8 },
  { strongsId: 'G4137', originalWord: 'πληρόω', transliteration: 'pleroo', pronunciation: p("play-ro'-o"), shortDefinition: 'to fill, to fulfill, to complete', fullDefinition: p("To fill, to fulfill, to complete, to accomplish. Used of fulfilling prophecies, completing time, and filling with the Spirit."), language: 'greek', partOfSpeech: 'verb', usageCount: 87, crossReferences: 'Matthew 5:17, John 12:38' },
  { strongsId: 'G4383', originalWord: 'πρόσωπον', transliteration: 'prosopon', pronunciation: p("pros'-o-pon"), shortDefinition: 'face, countenance, presence', fullDefinition: p("Face, countenance, presence, person. Used literally of the face and figuratively of one's presence or person."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'neuter', number: 'singular', usageCount: 78 },
  { strongsId: 'G4521', originalWord: 'σάββατον', transliteration: 'sabbaton', pronunciation: p("sab'-bat-on"), shortDefinition: 'Sabbath, week', fullDefinition: p("Sabbath, the seventh day of rest; also used for a week. Central to Jewish worship and a point of contention in Jesus' ministry."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'neuter', number: 'singular', usageCount: 68 },
  { strongsId: 'G4678', originalWord: 'σοφία', transliteration: 'sophia', pronunciation: p("sof-ee'-ah"), shortDefinition: 'wisdom, insight, skill', fullDefinition: p("Wisdom, insight, practical skill, divine wisdom. Used of both human wisdom and the wisdom of God revealed in Christ."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'feminine', number: 'singular', usageCount: 51, crossReferences: 'Proverbs 1:7, James 3:17' },
  { strongsId: 'G4690', originalWord: 'σπέρμα', transliteration: 'sperma', pronunciation: p("sper'-mah"), shortDefinition: 'seed, offspring, descendant', fullDefinition: p("Seed, offspring, descendant, progeny. Used literally of plant seed and figuratively of spiritual lineage and the Word of God."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'neuter', number: 'singular', usageCount: 44 },
  { strongsId: 'G4725', originalWord: 'στέφανος', transliteration: 'stephanos', pronunciation: p("stef'-an-os"), shortDefinition: "crown, wreath, victor's crown", fullDefinition: p("Crown, wreath, victor's garland. Used of the crown given to victors and of the crown of life for the faithful."), language: 'greek', partOfSpeech: 'noun', grammaticalCase: 'nominative', gender: 'masculine', number: 'singular', usageCount: 18 },
  { strongsId: 'G4982', originalWord: 'σῴζω', transliteration: 'sozo', pronunciation: p("sode'-zo"), shortDefinition: 'to save, to deliver, to heal', fullDefinition: p("To save, to deliver, to heal, to preserve. A central soteriological term for salvation from sin and its consequences."), language: 'greek', partOfSpeech: 'verb', usageCount: 107, crossReferences: 'Romans 10:9, Ephesians 2:8' },

  // ── NEW HEBREW ENTRIES (15+) ───────────────────────────────
  { strongsId: 'H1288', originalWord: 'בָּרַךְ', transliteration: 'barak', pronunciation: 'baw-rak', shortDefinition: 'to bless, to kneel, to praise', fullDefinition: p("To bless, to endue with power, to kneel in adoration. Used extensively of God blessing humanity and of people blessing God in praise."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 330 },
  { strongsId: 'H1289', originalWord: 'בְּרָכָה', transliteration: 'berakah', pronunciation: 'ber-aw-kaw', shortDefinition: 'blessing, gift, praise', fullDefinition: p("Blessing, gift, benediction, praise. Refers to spoken blessing, the gift of prosperity, and praise offered to God."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 69 },
  { strongsId: 'H1571', originalWord: 'גַּם', transliteration: 'gam', pronunciation: 'gam', shortDefinition: 'also, even, indeed, moreover', fullDefinition: p("Also, even, indeed, moreover, likewise. A common Hebrew particle used for addition and emphasis."), language: 'hebrew', partOfSpeech: 'conjunction', usageCount: 800 },
  { strongsId: 'H1696', originalWord: 'דָּבַר', transliteration: 'dabar', pronunciation: 'daw-bar', shortDefinition: 'to speak, to declare, to command', fullDefinition: p("To speak, to declare, to command, to promise. One of the most common Hebrew verbs for divine and human communication."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 1140 },
  { strongsId: 'H1697', originalWord: 'דָּבָר', transliteration: 'dabar', pronunciation: 'daw-bawr', shortDefinition: 'word, thing, matter, event', fullDefinition: p("Word, thing, matter, event, commandment. Used of God's spoken word, the Ten Commandments, and any matter or affair."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', usageCount: 1455, crossReferences: 'Psalm 119:105' },
  { strongsId: 'H3068', originalWord: 'יְהוָה', transliteration: 'YHWH', pronunciation: 'yeh-ho-vaw', shortDefinition: 'LORD, Yahweh, the proper name of God', fullDefinition: p("YHWH, Yahweh, the LORD. The sacred personal name of the God of Israel, revealed to Moses at the burning bush."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', usageCount: 6519, crossReferences: 'Exodus 3:15, Deuteronomy 6:4' },
  { strongsId: 'H3467', originalWord: 'יָשַׁע', transliteration: 'yasha', pronunciation: 'yaw-shah', shortDefinition: 'to save, to deliver, to help', fullDefinition: p("To save, to deliver, to help, to give victory. Used of God's intervention to rescue His people from danger and oppression."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 213 },
  { strongsId: 'H3444', originalWord: 'יְשׁוּעָה', transliteration: 'yeshuah', pronunciation: 'yesh-oo-aw', shortDefinition: 'salvation, deliverance, victory', fullDefinition: p("Salvation, deliverance, victory, welfare. Used of God's saving acts, both temporal deliverance and eternal salvation."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 78 },
  { strongsId: 'H5315', originalWord: 'נֶפֶשׁ', transliteration: 'nephesh', pronunciation: 'neh-fesh', shortDefinition: 'soul, life, being, person', fullDefinition: p("Soul, life, self, being, person, living creature. One of the most important OT words for the inner life and essence of a person."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 753 },
  { strongsId: 'H6680', originalWord: 'צָוָה', transliteration: 'tsavah', pronunciation: 'tsaw-vaw', shortDefinition: 'to command, to charge, to appoint', fullDefinition: p("To command, to charge, to appoint, to ordain. Used of God giving commands to His people and of human authority figures issuing orders."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 494 },
  { strongsId: 'H6682', originalWord: 'צְוָה', transliteration: 'tsavah', pronunciation: 'tsev-aw', shortDefinition: 'command, commandment, order', fullDefinition: p("Command, commandment, order, decree. Refers to a specific command or ordinance given by authority."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 9 },
  { strongsId: 'H6965', originalWord: 'קוּם', transliteration: 'kum', pronunciation: 'koom', shortDefinition: 'to arise, to stand, to rise up', fullDefinition: p("To arise, to stand up, to rise, to come on the scene. Used both literally of standing and figuratively of fulfilling a promise."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 627 },
  { strongsId: 'H7307', originalWord: 'רוּחַ', transliteration: 'ruach', pronunciation: "roo'-akh", shortDefinition: 'spirit, wind, breath', fullDefinition: p("Spirit, wind, breath, life-force. Used of God's Spirit, the human spirit, and the physical wind."), language: 'hebrew', partOfSpeech: 'noun', gender: 'feminine', number: 'singular', usageCount: 378 },
  { strongsId: 'H8085', originalWord: 'שָׁמַע', transliteration: 'shama', pronunciation: 'shaw-mah', shortDefinition: 'to hear, to listen, to obey', fullDefinition: p("To hear, to listen, to obey, to understand. Central to the Shema (Deuteronomy 6:4) and Israel's covenant relationship with God."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 1165, crossReferences: 'Deuteronomy 6:4' },
  { strongsId: 'H8089', originalWord: 'שֹׁמַע', transliteration: 'shoma', pronunciation: "sho'-mah", shortDefinition: 'report, news, hearing', fullDefinition: p("Report, news, hearing, fame. Refers to something heard, a report, or the sense of hearing itself."), language: 'hebrew', partOfSpeech: 'noun', gender: 'masculine', number: 'singular', usageCount: 4 },
  { strongsId: 'H8104', originalWord: 'שָׁמַר', transliteration: 'shamar', pronunciation: 'shaw-mar', shortDefinition: 'to keep, to guard, to watch, to preserve', fullDefinition: p("To keep, to guard, to watch, to observe, to preserve. Used of keeping God's commandments and of God's protective care."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 468 },
  { strongsId: 'H8354', originalWord: 'שָׁתָה', transliteration: 'shathah', pronunciation: 'shaw-thaw', shortDefinition: 'to drink', fullDefinition: p("To drink. Used literally of drinking water or wine and metaphorically of drinking the cup of God's judgment."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 220 },

  // ── EXTRA HEBREW for Psalm 23 / Romans mapping support ──────
  { strongsId: 'H3808', originalWord: 'לֹא', transliteration: 'lo', pronunciation: 'lo', shortDefinition: 'not, no, never', fullDefinition: p("Not, no, never, nothing. The standard Hebrew negative particle used for negation of verbs and statements."), language: 'hebrew', partOfSpeech: 'adverb', usageCount: 5190 },
  { strongsId: 'H2637', originalWord: 'חָסֵר', transliteration: 'chaser', pronunciation: 'khaw-sare', shortDefinition: 'to lack, to be without, to want', fullDefinition: p("To lack, to be without, to need, to decrease. Used of physical need and spiritual poverty."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 120 },
  { strongsId: 'H7462', originalWord: 'רָעָה', transliteration: 'raah', pronunciation: 'raw-aw', shortDefinition: 'to shepherd, to pasture, to tend', fullDefinition: p("To shepherd, to pasture, to tend, to graze. Used literally of shepherding flocks and metaphorically of God shepherding His people."), language: 'hebrew', partOfSpeech: 'verb', usageCount: 173 },
];
const VERSE_WORDS_GENESIS_1_1 = [
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 1, surfaceText: 'In', strongsId: 'H7225', lemma: 'reshith', morphology: 'prep' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 2, surfaceText: 'the', strongsId: 'H0430', lemma: 'elohim', morphology: 'art' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 3, surfaceText: 'beginning', strongsId: 'H7225', lemma: 'reshith', morphology: 'noun-fs' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 4, surfaceText: 'God', strongsId: 'H0430', lemma: 'elohim', morphology: 'noun-mp' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 5, surfaceText: 'created', strongsId: 'H1254', lemma: 'bara', morphology: 'verb-qal-perf-3ms' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 6, surfaceText: 'the', strongsId: 'H0804', lemma: 'shamayim', morphology: 'art' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 7, surfaceText: 'heavens', strongsId: 'H0804', lemma: 'shamayim', morphology: 'noun-mp' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 8, surfaceText: 'and', strongsId: 'H1254', lemma: 'bara', morphology: 'conj' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 9, surfaceText: 'the', strongsId: 'H0776', lemma: 'erets', morphology: 'art' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 1, wordOrder: 10, surfaceText: 'earth', strongsId: 'H0776', lemma: 'erets', morphology: 'noun-fs' },
];

const VERSE_WORDS_GENESIS_1_2 = [
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 1, surfaceText: 'Now', strongsId: 'H1961', lemma: 'hayah', morphology: 'conj' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 2, surfaceText: 'the', strongsId: 'H0776', lemma: 'erets', morphology: 'art' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 3, surfaceText: 'earth', strongsId: 'H0776', lemma: 'erets', morphology: 'noun-fs' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 4, surfaceText: 'was', strongsId: 'H1961', lemma: 'hayah', morphology: 'verb-qal-perf-3fs' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 5, surfaceText: 'formless', strongsId: 'H8414', lemma: 'tohu', morphology: 'noun-ms' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 6, surfaceText: 'and', strongsId: 'H0922', lemma: 'bohu', morphology: 'conj' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 7, surfaceText: 'void', strongsId: 'H0922', lemma: 'bohu', morphology: 'noun-ms' },
  { translation: 'Berean', bookName: 'Genesis', chapter: 1, verse: 2, wordOrder: 8, surfaceText: '.', strongsId: null, lemma: null, morphology: null },
];

const VERSE_WORDS_JOHN_3_16 = [
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 1, surfaceText: 'For', strongsId: 'G1063', lemma: 'gar', morphology: 'conj' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 2, surfaceText: 'God', strongsId: 'G2316', lemma: 'theos', morphology: 'noun-nm' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 3, surfaceText: 'so', strongsId: 'G3779', lemma: 'houtos', morphology: 'adv' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 4, surfaceText: 'loved', strongsId: 'G0025', lemma: 'agapao', morphology: 'verb-aor-act-ind-3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 5, surfaceText: 'the', strongsId: 'G2889', lemma: 'kosmos', morphology: 'art' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 6, surfaceText: 'world', strongsId: 'G2889', lemma: 'kosmos', morphology: 'noun-am' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 7, surfaceText: 'that', strongsId: 'G3754', lemma: 'hoti', morphology: 'conj' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 8, surfaceText: 'He', strongsId: 'G0846', lemma: 'autos', morphology: 'ppro-nm3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 9, surfaceText: 'gave', strongsId: 'G1325', lemma: 'didomi', morphology: 'verb-aor-act-ind-3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 10, surfaceText: 'His', strongsId: 'G0846', lemma: 'autos', morphology: 'ppro-gm3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 11, surfaceText: 'one', strongsId: 'G1520', lemma: 'heis', morphology: 'adj-am' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 12, surfaceText: 'and', strongsId: 'G3439', lemma: 'monogenes', morphology: 'conj' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 13, surfaceText: 'only', strongsId: 'G3439', lemma: 'monogenes', morphology: 'adj-am' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 14, surfaceText: 'Son', strongsId: 'G5207', lemma: 'huios', morphology: 'noun-am' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 15, surfaceText: 'that', strongsId: 'G3754', lemma: 'hoti', morphology: 'conj' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 16, surfaceText: 'whoever', strongsId: 'G3956', lemma: 'pas', morphology: 'adj-nm' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 17, surfaceText: 'believes', strongsId: 'G4100', lemma: 'pisteuo', morphology: 'verb-pres-act-part-nm' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 18, surfaceText: 'in', strongsId: 'G1722', lemma: 'en', morphology: 'prep' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 19, surfaceText: 'Him', strongsId: 'G0846', lemma: 'autos', morphology: 'ppro-am3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 20, surfaceText: 'shall', strongsId: 'G3361', lemma: 'me', morphology: 'part' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 21, surfaceText: 'not', strongsId: 'G3361', lemma: 'me', morphology: 'part' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 22, surfaceText: 'perish', strongsId: 'G0622', lemma: 'apollumi', morphology: 'verb-aor-mid-subj-3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 23, surfaceText: 'but', strongsId: 'G0235', lemma: 'alla', morphology: 'conj' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 24, surfaceText: 'have', strongsId: 'G2192', lemma: 'echo', morphology: 'verb-pres-act-subj-3s' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 25, surfaceText: 'eternal', strongsId: 'G0166', lemma: 'aionios', morphology: 'adj-afs' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 26, surfaceText: 'life', strongsId: 'G2222', lemma: 'zoe', morphology: 'noun-afs' },
  { translation: 'Berean', bookName: 'John', chapter: 3, verse: 16, wordOrder: 27, surfaceText: '.', strongsId: null, lemma: null, morphology: null },
];

const VERSE_WORDS_PSALM_23_1 = [
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 1, surfaceText: 'The', strongsId: null, lemma: null, morphology: 'art' },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 2, surfaceText: 'LORD', strongsId: 'H3068', lemma: 'YHWH', morphology: 'noun-proper' },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 3, surfaceText: 'is', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 4, surfaceText: 'my', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 5, surfaceText: 'shepherd', strongsId: 'H7462', lemma: 'raah', morphology: 'noun-ms' },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 6, surfaceText: ';', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 7, surfaceText: 'I', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 8, surfaceText: 'shall', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 9, surfaceText: 'not', strongsId: 'H3808', lemma: 'lo', morphology: 'adv' },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 10, surfaceText: 'want', strongsId: 'H2637', lemma: 'chaser', morphology: 'verb' },
  { translation: 'Berean', bookName: 'Psalms', chapter: 23, verse: 1, wordOrder: 11, surfaceText: '.', strongsId: null, lemma: null, morphology: null },
];

const VERSE_WORDS_ROMANS_8_28 = [
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 1, surfaceText: 'And', strongsId: null, lemma: null, morphology: 'conj' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 2, surfaceText: 'we', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 3, surfaceText: 'know', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 4, surfaceText: 'that', strongsId: 'G3754', lemma: 'hoti', morphology: 'conj' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 5, surfaceText: 'God', strongsId: 'G2316', lemma: 'theos', morphology: 'noun-nm' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 6, surfaceText: 'works', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 7, surfaceText: 'all', strongsId: 'G3956', lemma: 'pas', morphology: 'adj-am' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 8, surfaceText: 'things', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 9, surfaceText: 'together', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 10, surfaceText: 'for', strongsId: null, lemma: null, morphology: 'prep' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 11, surfaceText: 'the', strongsId: null, lemma: null, morphology: 'art' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 12, surfaceText: 'good', strongsId: 'G0016', lemma: 'agathosyne', morphology: 'noun-afs' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 13, surfaceText: 'of', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 14, surfaceText: 'those', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 15, surfaceText: 'who', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 16, surfaceText: 'love', strongsId: 'G0025', lemma: 'agapao', morphology: 'verb-pres-act-part-gm' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 17, surfaceText: 'Him', strongsId: 'G0846', lemma: 'autos', morphology: 'ppro-am3s' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 18, surfaceText: ',', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 19, surfaceText: 'who', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 20, surfaceText: 'are', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 21, surfaceText: 'called', strongsId: 'G2822', lemma: 'kletos', morphology: 'adj-nmp' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 22, surfaceText: 'according', strongsId: 'G2648', lemma: 'kata', morphology: 'prep' },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 23, surfaceText: 'to', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 24, surfaceText: 'His', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 25, surfaceText: 'purpose', strongsId: null, lemma: null, morphology: null },
  { translation: 'Berean', bookName: 'Romans', chapter: 8, verse: 28, wordOrder: 26, surfaceText: '.', strongsId: null, lemma: null, morphology: null },
];

async function seed() {
  console.log('Seeding Strong\'s dictionary...');

  for (const entry of STRONGS_ENTRIES) {
    await prisma.strongsDictionary.upsert({
      where: { strongsId: entry.strongsId },
      update: entry,
      create: entry,
    });
  }
  console.log(`  ✓ ${STRONGS_ENTRIES.length} Strong's entries seeded`);

  const allVerseWords = [
    ...VERSE_WORDS_GENESIS_1_1,
    ...VERSE_WORDS_GENESIS_1_2,
    ...VERSE_WORDS_JOHN_3_16,
    ...VERSE_WORDS_PSALM_23_1,
    ...VERSE_WORDS_ROMANS_8_28,
  ];

  // Clear existing verse words first to prevent duplicates
  await prisma.verseWord.deleteMany({});
  console.log('  ✓ Cleared existing verse word mappings');

  await prisma.verseWord.createMany({
    data: allVerseWords,
  });
  console.log(`  ✓ ${allVerseWords.length} verse word mappings seeded`);

  console.log('Seed complete!');
}

seed()
  .catch(e => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
