import { PrismaClient } from "@prisma/client";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../.env") });

const prisma = new PrismaClient();

const questions = [
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — EASY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "How many days did God take to create the heavens and the earth?",
    optionsJson: JSON.stringify(["Five", "Six", "Seven", "Ten"]),
    correctAnswer: 1,
    explanation: "God created the heavens and the earth in six days and rested on the seventh day (Genesis 1).",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 31,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did God create on the fourth day?",
    optionsJson: JSON.stringify(["Trees and plants", "Fish and birds", "The sun, moon, and stars", "Land animals"]),
    correctAnswer: 2,
    explanation: "On the fourth day, God created the sun, moon, and stars to separate day from night and mark seasons (Genesis 1:14-19).",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did Adam and Eve eat that led to their expulsion from the Garden of Eden?",
    optionsJson: JSON.stringify(["Fruit from the tree of life", "Fruit from the tree of the knowledge of good and evil", "Bread from heaven", "Grapes from the vine"]),
    correctAnswer: 1,
    explanation: "Adam and Eve ate from the tree of the knowledge of good and evil, which God had commanded them not to eat (Genesis 3:6).",
    bookName: "Genesis",
    chapter: 3,
    verseNumber: 6,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who built the ark to survive the great flood?",
    optionsJson: JSON.stringify(["Abraham", "Moses", "Noah", "David"]),
    correctAnswer: 2,
    explanation: "God instructed Noah to build an ark to save his family and the animals from the flood (Genesis 6-7).",
    bookName: "Genesis",
    chapter: 6,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "How many pairs of each clean animal did God tell Noah to take on the ark?",
    optionsJson: JSON.stringify(["One pair", "Seven pairs", "One of each kind", "Four pairs"]),
    correctAnswer: 1,
    explanation: "God told Noah to take seven pairs (fourteen) of every clean animal and one pair of unclean animals (Genesis 7:2-3).",
    bookName: "Genesis",
    chapter: 7,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What sign did God give as a covenant that He would never again flood the whole earth?",
    optionsJson: JSON.stringify(["A star", "A dove", "A rainbow", "A fire"]),
    correctAnswer: 2,
    explanation: "God set the rainbow in the clouds as a sign of His covenant never to destroy the earth by flood again (Genesis 9:13-16).",
    bookName: "Genesis",
    chapter: 9,
    verseNumber: 13,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did the people build at Babel to make a name for themselves?",
    optionsJson: JSON.stringify(["A great army", "A tower", "A walled city", "A golden statue"]),
    correctAnswer: 1,
    explanation: "The people built a tower in Shinar (Babel) to reach the heavens and make a name for themselves. God confused their language (Genesis 11:1-9).",
    bookName: "Genesis",
    chapter: 11,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which patriarch was promised by God that his descendants would be as numerous as the stars?",
    optionsJson: JSON.stringify(["Moses", "David", "Abraham", "Solomon"]),
    correctAnswer: 2,
    explanation: "God brought Abraham outside and told him to count the stars, saying his descendants would be that numerous (Genesis 15:5).",
    bookName: "Genesis",
    chapter: 15,
    verseNumber: 5,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What was the name of Abraham's son born to Hagar?",
    optionsJson: JSON.stringify(["Isaac", "Jacob", "Ishmael", "Esau"]),
    correctAnswer: 2,
    explanation: "Ishmael was born to Abraham and Hagar, Sarah's maidservant (Genesis 16:15).",
    bookName: "Genesis",
    chapter: 16,
    verseNumber: 15,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "How many years did the Israelites wander in the wilderness?",
    optionsJson: JSON.stringify(["20 years", "40 years", "70 years", "10 years"]),
    correctAnswer: 1,
    explanation: "The Israelites wandered in the wilderness for 40 years because of their unbelief and refusal to enter the Promised Land (Numbers 14:33-34).",
    bookName: "Numbers",
    chapter: 14,
    verseNumber: 33,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who received the Ten Commandments on Mount Sinai?",
    optionsJson: JSON.stringify(["Aaron", "Joshua", "Moses", "Elijah"]),
    correctAnswer: 2,
    explanation: "Moses received the Ten Commandments from God on Mount Sinai (Exodus 20:1-17).",
    bookName: "Exodus",
    chapter: 20,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What was the first plague that God sent upon Egypt?",
    optionsJson: JSON.stringify(["Frogs", "Darkness", "Water turned to blood", "Boils"]),
    correctAnswer: 2,
    explanation: "The first plague was turning the Nile River and all water in Egypt into blood (Exodus 7:14-24).",
    bookName: "Exodus",
    chapter: 7,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which sea did the Israelites cross when fleeing from Egypt?",
    optionsJson: JSON.stringify(["Mediterranean Sea", "Red Sea", "Dead Sea", "Sea of Galilee"]),
    correctAnswer: 1,
    explanation: "God parted the Red Sea so the Israelites could cross on dry ground, then brought the waters back on the pursuing Egyptians (Exodus 14).",
    bookName: "Exodus",
    chapter: 14,
    verseNumber: 21,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did God provide from heaven to feed the Israelites in the wilderness?",
    optionsJson: JSON.stringify(["Bread from angels", "Manna", "Quail", "Both manna and quail"]),
    correctAnswer: 3,
    explanation: "God provided both manna (bread from heaven) and quail to feed the Israelites in the wilderness (Exodus 16).",
    bookName: "Exodus",
    chapter: 16,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who led the Israelites across the Jordan River into the Promised Land after Moses died?",
    optionsJson: JSON.stringify(["Caleb", "Joshua", "Samuel", "Elijah"]),
    correctAnswer: 1,
    explanation: "Joshua succeeded Moses and led the Israelites across the Jordan River to conquer the Promised Land (Joshua 1-3).",
    bookName: "Joshua",
    chapter: 1,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which city's walls fell down after the Israelites marched around them for seven days?",
    optionsJson: JSON.stringify(["Jerusalem", "Jericho", "Ai", "Hebron"]),
    correctAnswer: 1,
    explanation: "The walls of Jericho fell after the Israelites marched around the city once a day for six days and seven times on the seventh day (Joshua 6).",
    bookName: "Joshua",
    chapter: 6,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who defeated the giant Goliath?",
    optionsJson: JSON.stringify(["Saul", "Jonathan", "David", "Samson"]),
    correctAnswer: 2,
    explanation: "David, a young shepherd, defeated the Philistine giant Goliath with a sling and a stone (1 Samuel 17).",
    bookName: "1 Samuel",
    chapter: 17,
    verseNumber: 50,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the first king of Israel?",
    optionsJson: JSON.stringify(["David", "Saul", "Solomon", "Samuel"]),
    correctAnswer: 1,
    explanation: "Saul was the first king of Israel, anointed by the prophet Samuel (1 Samuel 10:1).",
    bookName: "1 Samuel",
    chapter: 10,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who built the first Temple in Jerusalem?",
    optionsJson: JSON.stringify(["David", "Solomon", "Hezekiah", "Zerubbabel"]),
    correctAnswer: 1,
    explanation: "King Solomon built the first Temple in Jerusalem, though his father David had prepared the materials (1 Kings 6).",
    bookName: "1 Kings",
    chapter: 6,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which prophet was taken up to heaven in a whirlwind?",
    optionsJson: JSON.stringify(["Elisha", "Elijah", "Isaiah", "Jeremiah"]),
    correctAnswer: 1,
    explanation: "Elijah was taken up to heaven in a chariot of fire by a whirlwind (2 Kings 2:11).",
    bookName: "2 Kings",
    chapter: 2,
    verseNumber: 11,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was thrown into a den of lions but was protected by God?",
    optionsJson: JSON.stringify(["Jeremiah", "Daniel", "Shadrach", "Joseph"]),
    correctAnswer: 1,
    explanation: "Daniel was thrown into a den of lions for praying to God against the king's decree, but God shut the lions' mouths (Daniel 6).",
    bookName: "Daniel",
    chapter: 6,
    verseNumber: 16,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Which three young men were thrown into a fiery furnace but were not burned?",
    optionsJson: JSON.stringify(["Daniel, Hananiah, and Mishael", "Shadrach, Meshach, and Abednego", "Meshach, Daniel, and Azariah", "Hananiah, Azariah, and Michael"]),
    correctAnswer: 1,
    explanation: "Shadrach, Meshach, and Abednego were thrown into the fiery furnace for refusing to worship Nebuchadnezzar's golden image and survived (Daniel 3).",
    bookName: "Daniel",
    chapter: 3,
    verseNumber: 12,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who interpreted King Nebuchadnezzar's dream of the great statue?",
    optionsJson: JSON.stringify(["Daniel", "Isaiah", "Ezekiel", "Jeremiah"]),
    correctAnswer: 0,
    explanation: "Daniel interpreted Nebuchadnezzar's dream of the statue made of gold, silver, bronze, iron, and clay (Daniel 2).",
    bookName: "Daniel",
    chapter: 2,
    verseNumber: 31,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the strong man who lost his strength when his hair was cut?",
    optionsJson: JSON.stringify(["Gideon", "Samson", "Jephthah", "Abimelech"]),
    correctAnswer: 1,
    explanation: "Samson's supernatural strength came from his Nazirite vow. Delilah cut his hair, and he lost his strength (Judges 16:17-19).",
    bookName: "Judges",
    chapter: 16,
    verseNumber: 17,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the first woman created?",
    optionsJson: JSON.stringify(["Sarah", "Rebekah", "Eve", "Rachel"]),
    correctAnswer: 2,
    explanation: "Eve was the first woman, created by God from Adam's rib (Genesis 2:21-22).",
    bookName: "Genesis",
    chapter: 2,
    verseNumber: 22,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What did Cain do to his brother Abel?",
    optionsJson: JSON.stringify(["He deceived him", "He killed him", "He stole from him", "He exiled him"]),
    correctAnswer: 1,
    explanation: "Cain killed his brother Abel out of jealousy because God accepted Abel's offering but not Cain's (Genesis 4:8).",
    bookName: "Genesis",
    chapter: 4,
    verseNumber: 8,
    category: "old-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — MEDIUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What did Jacob receive from his father Isaac by deceiving him?",
    optionsJson: JSON.stringify(["The family wealth", "The birthright blessing", "The land of Canaan", "The priesthood"]),
    correctAnswer: 1,
    explanation: "Jacob, disguised as his brother Esau, received the blessing of the firstborn from his blind father Isaac (Genesis 27).",
    bookName: "Genesis",
    chapter: 27,
    verseNumber: 27,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many plagues did God send upon Egypt before Pharaoh released the Israelites?",
    optionsJson: JSON.stringify(["7", "10", "12", "3"]),
    correctAnswer: 1,
    explanation: "God sent ten plagues upon Egypt: blood, frogs, gnats, flies, livestock disease, boils, hail, locusts, darkness, and the death of the firstborn (Exodus 7-12).",
    bookName: "Exodus",
    chapter: 7,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "What was the name of Moses' brother who served as his spokesperson?",
    optionsJson: JSON.stringify(["Aaron", "Joshua", "Caleb", "Hur"]),
    correctAnswer: 0,
    explanation: "Aaron, Moses' brother, was appointed by God to speak for Moses because Moses felt inadequate as a speaker (Exodus 4:14-16).",
    bookName: "Exodus",
    chapter: 4,
    verseNumber: 14,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many books are in the Torah (the first five books of the Old Testament)?",
    optionsJson: JSON.stringify(["Three", "Five", "Seven", "Ten"]),
    correctAnswer: 1,
    explanation: "The Torah consists of five books: Genesis, Exodus, Leviticus, Numbers, and Deuteronomy.",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet was swallowed by a great fish?",
    optionsJson: JSON.stringify(["Elijah", "Jonah", "Daniel", "Habakkuk"]),
    correctAnswer: 1,
    explanation: "Jonah was swallowed by a great fish (whale) when he tried to flee from God's command to preach to Nineveh (Jonah 1:17).",
    bookName: "Jonah",
    chapter: 1,
    verseNumber: 17,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the mother of the prophet Samuel?",
    optionsJson: JSON.stringify(["Hannah", "Leah", "Rachel", "Miriam"]),
    correctAnswer: 0,
    explanation: "Hannah, who was barren, prayed earnestly for a son and promised to dedicate him to the Lord. God gave her Samuel (1 Samuel 1).",
    bookName: "1 Samuel",
    chapter: 1,
    verseNumber: 20,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which king of Israel was known for his wisdom?",
    optionsJson: JSON.stringify(["David", "Saul", "Solomon", "Hezekiah"]),
    correctAnswer: 2,
    explanation: "King Solomon was renowned for his wisdom, which God granted him when he asked for wisdom rather than wealth or power (1 Kings 3).",
    bookName: "1 Kings",
    chapter: 3,
    verseNumber: 12,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "What object did the Israelites carry into battle that represented God's presence?",
    optionsJson: JSON.stringify(["The bronze serpent", "The Ark of the Covenant", "The golden lampstand", "The altar of incense"]),
    correctAnswer: 1,
    explanation: "The Ark of the Covenant represented God's presence among His people and was carried before the Israelites into battle (Joshua 6:4-6).",
    bookName: "Joshua",
    chapter: 6,
    verseNumber: 4,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "How many days and nights did Elijah travel to Mount Horeb after being fed by an angel?",
    optionsJson: JSON.stringify(["10 days", "40 days and 40 nights", "7 days", "3 days"]),
    correctAnswer: 1,
    explanation: "After being fed by an angel, Elijah traveled 40 days and 40 nights to Mount Horeb (Sinai) (1 Kings 19:8).",
    bookName: "1 Kings",
    chapter: 19,
    verseNumber: 8,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which prophet wrote the book that describes a valley of dry bones coming to life?",
    optionsJson: JSON.stringify(["Isaiah", "Jeremiah", "Ezekiel", "Zechariah"]),
    correctAnswer: 2,
    explanation: "Ezekiel's vision of the valley of dry bones symbolizes the restoration of Israel (Ezekiel 37:1-14).",
    bookName: "Ezekiel",
    chapter: 37,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which book of the Bible contains the story of Ruth?",
    optionsJson: JSON.stringify(["Judges", "Ruth", "1 Samuel", "Joshua"]),
    correctAnswer: 1,
    explanation: "The book of Ruth tells the story of Ruth, a Moabite woman who became the great-grandmother of King David.",
    bookName: "Ruth",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "easy",
  },
  {
    question: "How many Psalms are in the book of Psalms?",
    optionsJson: JSON.stringify(["100", "150", "175", "120"]),
    correctAnswer: 1,
    explanation: "The book of Psalms contains 150 songs and prayers, many attributed to King David.",
    bookName: "Psalms",
    chapter: 150,
    verseNumber: 6,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which method did Gideon use to confirm God's promise of victory?",
    optionsJson: JSON.stringify(["Burning a sacrifice", "A fleece of wool", "A dream", "Casting lots"]),
    correctAnswer: 1,
    explanation: "Gideon placed a fleece of wool on the threshing floor and asked God to make it wet with dew while the ground remained dry, then the reverse (Judges 6:36-40).",
    bookName: "Judges",
    chapter: 6,
    verseNumber: 37,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Which Persian king allowed the Jews to return and rebuild Jerusalem?",
    optionsJson: JSON.stringify(["Darius", "Cyrus", "Artaxerxes", "Xerxes"]),
    correctAnswer: 1,
    explanation: "King Cyrus of Persia issued a decree allowing the Jewish exiles to return to Jerusalem and rebuild the Temple (Ezra 1:1-4).",
    bookName: "Ezra",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  {
    question: "Who was the prophet that confronted King David about his sin with Bathsheba?",
    optionsJson: JSON.stringify(["Nathan", "Samuel", "Gad", "Elijah"]),
    correctAnswer: 0,
    explanation: "The prophet Nathan confronted King David about his adultery with Bathsheba and the murder of Uriah using a parable (2 Samuel 12).",
    bookName: "2 Samuel",
    chapter: 12,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // OLD TESTAMENT — HARD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "In the book of Job, what were the names of Job's three friends who came to comfort him?",
    optionsJson: JSON.stringify(["Eliphaz, Bildad, and Zophar", "Elihu, Eliphaz, and Bildad", "Eliphaz, Elihu, and Zophar", "Bildad, Zophar, and Elihu"]),
    correctAnswer: 0,
    explanation: "Job's three friends were Eliphaz the Temanite, Bildad the Shuhite, and Zophar the Naamathite. A fourth friend, Elihu, spoke later (Job 2:11, 32:2).",
    bookName: "Job",
    chapter: 2,
    verseNumber: 11,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which prophet was told to marry a prostitute as a symbol of God's relationship with Israel?",
    optionsJson: JSON.stringify(["Isaiah", "Hosea", "Ezekiel", "Amos"]),
    correctAnswer: 1,
    explanation: "Hosea was commanded by God to marry Gomer, a prostitute, as a living symbol of Israel's unfaithfulness to God (Hosea 1:2).",
    bookName: "Hosea",
    chapter: 1,
    verseNumber: 2,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "How many chapters are in the book of Psalms attributed to the Sons of Korah?",
    optionsJson: JSON.stringify(["10", "11", "12", "7"]),
    correctAnswer: 1,
    explanation: "Eleven psalms are attributed to the Sons of Korah: Psalms 42, 44-49, 84-85, and 87-88.",
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which king of Israel had a dream of a tree that was cut down, symbolizing his temporary madness?",
    optionsJson: JSON.stringify(["Belshazzar", "Nebuchadnezzar", "Ahasuerus", "Jehoiakim"]),
    correctAnswer: 1,
    explanation: "King Nebuchadnezzar had a dream of a great tree that was cut down, which Daniel interpreted as Nebuchadnezzar's coming madness (Daniel 4).",
    bookName: "Daniel",
    chapter: 4,
    verseNumber: 10,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "Which minor prophet wrote the shortest book in the Old Testament?",
    optionsJson: JSON.stringify(["Nahum", "Obadiah", "Haggai", "Malachi"]),
    correctAnswer: 1,
    explanation: "The book of Obadiah is the shortest book in the Old Testament with only 21 verses.",
    bookName: "Obadiah",
    chapter: 1,
    verseNumber: 1,
    category: "old-testament",
    difficulty: "hard",
  },
  {
    question: "What was the name of the high priest who was also a judge over Israel?",
    optionsJson: JSON.stringify(["Aaron", "Eli", "Samuel", "Eleazar"]),
    correctAnswer: 1,
    explanation: "Eli served as both high priest and judge over Israel. He mentored the young Samuel (1 Samuel 1-4).",
    bookName: "1 Samuel",
    chapter: 1,
    verseNumber: 9,
    category: "old-testament",
    difficulty: "hard",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — EASY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "In which town was Jesus born?",
    optionsJson: JSON.stringify(["Nazareth", "Jerusalem", "Bethlehem", "Capernaum"]),
    correctAnswer: 2,
    explanation: "Jesus was born in Bethlehem of Judea, as prophesied by Micah (Micah 5:2, Matthew 2:1).",
    bookName: "Matthew",
    chapter: 2,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many apostles did Jesus choose?",
    optionsJson: JSON.stringify(["7", "10", "12", "14"]),
    correctAnswer: 2,
    explanation: "Jesus chose twelve apostles to be with Him and to be sent out to preach (Mark 3:14-19).",
    bookName: "Mark",
    chapter: 3,
    verseNumber: 14,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which disciple walked on water with Jesus?",
    optionsJson: JSON.stringify(["John", "James", "Peter", "Andrew"]),
    correctAnswer: 2,
    explanation: "Peter walked on water toward Jesus but began to sink when he doubted (Matthew 14:28-31).",
    bookName: "Matthew",
    chapter: 14,
    verseNumber: 29,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many fish did the disciples catch when Jesus performed the miraculous catch?",
    optionsJson: JSON.stringify(["153", "100", "99", "200"]),
    correctAnswer: 0,
    explanation: "The disciples caught 153 fish when Jesus directed them to cast the net on the right side (John 21:11).",
    bookName: "John",
    chapter: 21,
    verseNumber: 11,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did Jesus turn water into at the wedding in Cana?",
    optionsJson: JSON.stringify(["Milk", "Honey", "Wine", "Oil"]),
    correctAnswer: 2,
    explanation: "Jesus performed His first miracle by turning water into wine at a wedding in Cana (John 2:1-11).",
    bookName: "John",
    chapter: 2,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which parable tells the story of a son who left home and was welcomed back by his father?",
    optionsJson: JSON.stringify(["The Good Samaritan", "The Prodigal Son", "The Lost Sheep", "The Lost Coin"]),
    correctAnswer: 1,
    explanation: "The Parable of the Prodigal Son tells of a son who squandered his inheritance and was welcomed back by his forgiving father (Luke 15:11-32).",
    bookName: "Luke",
    chapter: 15,
    verseNumber: 11,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who betrayed Jesus for thirty pieces of silver?",
    optionsJson: JSON.stringify(["Peter", "Thomas", "Judas Iscariot", "Matthew"]),
    correctAnswer: 2,
    explanation: "Judas Iscariot, one of the twelve apostles, betrayed Jesus to the chief priests for thirty pieces of silver (Matthew 26:14-16).",
    bookName: "Matthew",
    chapter: 26,
    verseNumber: 15,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many days was Jesus in the tomb before His resurrection?",
    optionsJson: JSON.stringify(["Two days", "Three days", "Seven days", "Forty days"]),
    correctAnswer: 1,
    explanation: "Jesus was crucified on Friday and rose on Sunday — three days later, fulfilling His own prophecy (Matthew 12:40, 28:1-7).",
    bookName: "Matthew",
    chapter: 28,
    verseNumber: 6,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the Roman governor who condemned Jesus to crucifixion?",
    optionsJson: JSON.stringify(["Herod Antipas", "Pilate", "Caiaphas", "Felix"]),
    correctAnswer: 1,
    explanation: "Pontius Pilate, the Roman governor of Judea, condemned Jesus to crucifixion despite finding no fault in Him (John 19:4-16).",
    bookName: "John",
    chapter: 19,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Which book of the New Testament describes the day of Pentecost when the Holy Spirit descended?",
    optionsJson: JSON.stringify(["Romans", "Acts", "John", "Hebrews"]),
    correctAnswer: 1,
    explanation: "The book of Acts describes the Holy Spirit descending on the apostles at Pentecost with tongues of fire (Acts 2:1-4).",
    bookName: "Acts",
    chapter: 2,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who wrote most of the letters (epistles) in the New Testament?",
    optionsJson: JSON.stringify(["Peter", "John", "Paul", "James"]),
    correctAnswer: 2,
    explanation: "The Apostle Paul wrote 13 of the 27 books of the New Testament — the most of any author.",
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many books are in the New Testament?",
    optionsJson: JSON.stringify(["21", "27", "33", "39"]),
    correctAnswer: 1,
    explanation: "The New Testament contains 27 books: 4 Gospels, Acts, 21 Epistles, and Revelation.",
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "Who was the first Christian martyr, stoned for his faith?",
    optionsJson: JSON.stringify(["Peter", "James", "Stephen", "Philip"]),
    correctAnswer: 2,
    explanation: "Stephen, one of the seven deacons, became the first Christian martyr when he was stoned (Acts 7:54-60).",
    bookName: "Acts",
    chapter: 7,
    verseNumber: 59,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What did Jesus say to Satan when tempted to turn stones into bread?",
    optionsJson: JSON.stringify(["Away from me, Satan", "Man shall not live by bread alone", "Worship the Lord your God", "It is written"]),
    correctAnswer: 1,
    explanation: "Jesus quoted Deuteronomy 8:3: 'Man shall not live by bread alone, but by every word that comes from the mouth of God' (Matthew 4:4).",
    bookName: "Matthew",
    chapter: 4,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — MEDIUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which Gospel is the only one that includes the parables of the Good Samaritan and the Prodigal Son?",
    optionsJson: JSON.stringify(["Matthew", "Mark", "Luke", "John"]),
    correctAnswer: 2,
    explanation: "Only the Gospel of Luke contains the parables of the Good Samaritan (10:25-37) and the Prodigal Son (15:11-32).",
    bookName: "Luke",
    chapter: 10,
    verseNumber: 25,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "On which island was John when he received the Revelation?",
    optionsJson: JSON.stringify(["Patmos", "Cyprus", "Crete", "Malta"]),
    correctAnswer: 0,
    explanation: "John was on the island of Patmos when he received the vision that became the book of Revelation (Revelation 1:9).",
    bookName: "Revelation",
    chapter: 1,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What was Paul's name before his conversion on the road to Damascus?",
    optionsJson: JSON.stringify(["Simon", "Saul", "Silas", "Sergius"]),
    correctAnswer: 1,
    explanation: "Paul was originally called Saul, a Pharisee who persecuted Christians before his conversion (Acts 9:1-19).",
    bookName: "Acts",
    chapter: 9,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which disciple was a tax collector before following Jesus?",
    optionsJson: JSON.stringify(["Peter", "Andrew", "Matthew", "James"]),
    correctAnswer: 2,
    explanation: "Matthew (also called Levi) was a tax collector before Jesus called him to be a disciple (Matthew 9:9).",
    bookName: "Matthew",
    chapter: 9,
    verseNumber: 9,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "How many times did Peter deny knowing Jesus before the rooster crowed?",
    optionsJson: JSON.stringify(["Two times", "Three times", "Four times", "Once"]),
    correctAnswer: 1,
    explanation: "Jesus predicted that Peter would deny Him three times before the rooster crowed, which came true (Matthew 26:69-75).",
    bookName: "Matthew",
    chapter: 26,
    verseNumber: 34,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "What is the longest book in the New Testament?",
    optionsJson: JSON.stringify(["Matthew", "Luke", "Acts", "Romans"]),
    correctAnswer: 2,
    explanation: "The book of Acts is the longest book in the New Testament with 28 chapters and 1,007 verses.",
    bookName: "Acts",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which epistle contains the 'love chapter' that describes the attributes of love?",
    optionsJson: JSON.stringify(["Romans 12", "1 Corinthians 13", "Ephesians 5", "Colossians 3"]),
    correctAnswer: 1,
    explanation: "1 Corinthians 13 is known as the 'love chapter,' describing love as patient, kind, and enduring (1 Corinthians 13:4-8).",
    bookName: "1 Corinthians",
    chapter: 13,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "To whom did Jesus say 'You are Peter, and on this rock I will build My church'?",
    optionsJson: JSON.stringify(["James", "Peter", "Andrew", "John"]),
    correctAnswer: 1,
    explanation: "Jesus spoke these words to Peter after Peter confessed that Jesus is the Christ, the Son of the living God (Matthew 16:18).",
    bookName: "Matthew",
    chapter: 16,
    verseNumber: 18,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which of Paul's letters was written to a church in a city known for its temple to Artemis?",
    optionsJson: JSON.stringify(["Ephesians", "Philippians", "Colossians", "Thessalonians"]),
    correctAnswer: 0,
    explanation: "Ephesus was home to the Temple of Artemis, one of the Seven Wonders of the Ancient World. Paul wrote the letter to the Ephesians while in prison.",
    bookName: "Ephesians",
    chapter: 1,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "What was the name of the disciple who doubted Jesus' resurrection until he saw the wounds?",
    optionsJson: JSON.stringify(["Peter", "Thomas", "Philip", "Nathanael"]),
    correctAnswer: 1,
    explanation: "Thomas (called Didymus) said he would not believe unless he saw and touched Jesus' wounds, earning the nickname 'Doubting Thomas' (John 20:24-29).",
    bookName: "John",
    chapter: 20,
    verseNumber: 24,
    category: "new-testament",
    difficulty: "easy",
  },
  {
    question: "How many baskets of leftovers were collected after Jesus fed the 5,000?",
    optionsJson: JSON.stringify(["7", "12", "5", "3"]),
    correctAnswer: 1,
    explanation: "After feeding 5,000 men with five loaves and two fish, twelve baskets of leftovers were collected (Matthew 14:20).",
    bookName: "Matthew",
    chapter: 14,
    verseNumber: 20,
    category: "new-testament",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // NEW TESTAMENT — HARD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which New Testament book contains the 'Hall of Faith' chapter?",
    optionsJson: JSON.stringify(["Romans", "Galatians", "Hebrews", "James"]),
    correctAnswer: 2,
    explanation: "Hebrews 11 is the 'Hall of Faith' chapter, listing Old Testament figures who lived by faith.",
    bookName: "Hebrews",
    chapter: 11,
    verseNumber: 1,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "Which king ordered the massacre of infants in Bethlehem after Jesus' birth?",
    optionsJson: JSON.stringify(["Herod the Great", "Herod Antipas", "Caesar Augustus", "Archelaus"]),
    correctAnswer: 0,
    explanation: "King Herod the Great ordered the massacre of all male infants in Bethlehem under two years old to try to kill the newborn King of the Jews (Matthew 2:16).",
    bookName: "Matthew",
    chapter: 2,
    verseNumber: 16,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which disciple was also known as 'the disciple whom Jesus loved'?",
    optionsJson: JSON.stringify(["Peter", "John", "James", "Andrew"]),
    correctAnswer: 1,
    explanation: "John is traditionally identified as 'the disciple whom Jesus loved,' a phrase used five times in the Gospel of John (John 13:23, 19:26, 20:2, 21:7, 21:20).",
    bookName: "John",
    chapter: 13,
    verseNumber: 23,
    category: "new-testament",
    difficulty: "medium",
  },
  {
    question: "In Revelation, how many elders are described around God's throne?",
    optionsJson: JSON.stringify(["7", "12", "24", "144"]),
    correctAnswer: 2,
    explanation: "Twenty-four elders are seated around God's throne in heaven, wearing white robes and golden crowns (Revelation 4:4).",
    bookName: "Revelation",
    chapter: 4,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which of the Gospels does NOT contain the parable of the Good Samaritan?",
    optionsJson: JSON.stringify(["Matthew", "Mark", "Luke", "All three synoptic Gospels have it"]),
    correctAnswer: 2,
    explanation: "John's Gospel does not contain the parable of the Good Samaritan. In fact, John contains no parables at all, only metaphorical language like 'I am the vine.'",
    bookName: "Luke",
    chapter: 10,
    verseNumber: 30,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "How many times does the number 'seven' appear in the book of Revelation as a symbolic number?",
    optionsJson: JSON.stringify(["14 times", "54 times", "37 times", "Over 50 times"]),
    correctAnswer: 3,
    explanation: "The number seven appears over 50 times in Revelation, including seven churches, seven seals, seven trumpets, and seven bowls.",
    bookName: "Revelation",
    chapter: 1,
    verseNumber: 4,
    category: "new-testament",
    difficulty: "hard",
  },
  {
    question: "Which Roman centurion is mentioned for his great faith that Jesus commended?",
    optionsJson: JSON.stringify(["Cornelius", "The centurion at Capernaum", "The centurion at the cross", "Julius"]),
    correctAnswer: 1,
    explanation: "The centurion at Capernaum demonstrated great faith, telling Jesus that He only needed to speak the word for his servant to be healed (Matthew 8:5-13).",
    bookName: "Matthew",
    chapter: 8,
    verseNumber: 5,
    category: "new-testament",
    difficulty: "hard",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL BIBLE KNOWLEDGE — EASY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "How many books are in the entire Bible?",
    optionsJson: JSON.stringify(["66", "73", "39", "27"]),
    correctAnswer: 0,
    explanation: "The Bible contains 66 books: 39 in the Old Testament and 27 in the New Testament.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which language was most of the Old Testament written in?",
    optionsJson: JSON.stringify(["Aramaic", "Hebrew", "Greek", "Latin"]),
    correctAnswer: 1,
    explanation: "The Old Testament was primarily written in Hebrew, with small portions in Aramaic (Daniel 2:4-7:28, Ezra 4:8-6:18).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What language was the New Testament originally written in?",
    optionsJson: JSON.stringify(["Hebrew", "Aramaic", "Greek", "Latin"]),
    correctAnswer: 2,
    explanation: "The New Testament was written in Koine Greek, the common language of the eastern Mediterranean in the first century.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the longest book in the Bible?",
    optionsJson: JSON.stringify(["Isaiah", "Genesis", "Psalms", "Jeremiah"]),
    correctAnswer: 2,
    explanation: "The book of Psalms is the longest book in the Bible with 150 chapters (though Jeremiah has more words in the original Hebrew).",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "What is the shortest verse in the Bible?",
    optionsJson: JSON.stringify(["John 11:35", "Psalm 117:2", "1 Thessalonians 5:16", "Luke 1:38"]),
    correctAnswer: 0,
    explanation: "John 11:35 ('Jesus wept.') is the shortest verse in most English Bible translations.",
    bookName: "John",
    chapter: 11,
    verseNumber: 35,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which biblical figure is known for writing most of the Proverbs?",
    optionsJson: JSON.stringify(["David", "Solomon", "Moses", "Isaiah"]),
    correctAnswer: 1,
    explanation: "King Solomon is traditionally credited with writing most of the book of Proverbs and Ecclesiastes (Proverbs 1:1).",
    bookName: "Proverbs",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the first book of the Bible?",
    optionsJson: JSON.stringify(["Exodus", "Leviticus", "Genesis", "Job"]),
    correctAnswer: 2,
    explanation: "Genesis is the first book of the Bible, describing creation, the fall, and the patriarchs.",
    bookName: "Genesis",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the last book of the Bible?",
    optionsJson: JSON.stringify(["Jude", "Revelation", "Malachi", "John"]),
    correctAnswer: 1,
    explanation: "Revelation is the last book of the Bible, describing John's vision of the end times and the new creation.",
    bookName: "Revelation",
    chapter: 22,
    verseNumber: 21,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "Which mountain did Moses receive the Ten Commandments on?",
    optionsJson: JSON.stringify(["Mount Zion", "Mount Sinai", "Mount Carmel", "Mount Nebo"]),
    correctAnswer: 1,
    explanation: "Moses received the Ten Commandments from God on Mount Sinai (Exodus 19-20).",
    bookName: "Exodus",
    chapter: 19,
    verseNumber: 20,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What does the word 'Gospel' mean?",
    optionsJson: JSON.stringify(["History", "Good news", "Teaching", "Prophecy"]),
    correctAnswer: 1,
    explanation: "The word 'Gospel' comes from the Greek word 'euangelion,' meaning 'good news' — the good news of Jesus Christ.",
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the longest chapter in the Bible?",
    optionsJson: JSON.stringify(["Psalm 119", "Psalm 23", "Isaiah 53", "Genesis 1"]),
    correctAnswer: 0,
    explanation: "Psalm 119 is the longest chapter in the Bible with 176 verses, each focusing on the Word of God.",
    bookName: "Psalms",
    chapter: 119,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  {
    question: "What is the shortest chapter in the Bible?",
    optionsJson: JSON.stringify(["Psalm 117", "Psalm 1", "John 11", "Obadiah 1"]),
    correctAnswer: 0,
    explanation: "Psalm 117 is the shortest chapter in the Bible with only two verses: 'Praise the Lord, all you nations!'",
    bookName: "Psalms",
    chapter: 117,
    verseNumber: 1,
    category: "general",
    difficulty: "easy",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL BIBLE KNOWLEDGE — MEDIUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "Which Old Testament book does NOT mention God directly?",
    optionsJson: JSON.stringify(["Ecclesiastes", "Song of Solomon", "Esther", "Lamentations"]),
    correctAnswer: 2,
    explanation: "The book of Esther is the only book in the Bible that does not explicitly mention God.",
    bookName: "Esther",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "How many authors contributed to the writing of the Bible?",
    optionsJson: JSON.stringify(["About 40", "About 66", "About 27", "About 10"]),
    correctAnswer: 0,
    explanation: "The Bible was written by approximately 40 authors over a span of about 1,500 years, yet it tells one unified story.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Over approximately how many years was the Bible written?",
    optionsJson: JSON.stringify(["500 years", "1,000 years", "1,500 years", "2,000 years"]),
    correctAnswer: 2,
    explanation: "The Bible was written over approximately 1,500 years, from about 1400 BC to AD 90-100.",
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which apostle was a tentmaker by trade?",
    optionsJson: JSON.stringify(["Peter", "John", "Paul", "Barnabas"]),
    correctAnswer: 2,
    explanation: "Paul was a tentmaker by trade (Acts 18:3), which allowed him to support himself during his missionary journeys.",
    bookName: "Acts",
    chapter: 18,
    verseNumber: 3,
    category: "general",
    difficulty: "medium",
  },
  {
    question: "Which prophet wrote Lamentations?",
    optionsJson: JSON.stringify(["Isaiah", "Ezekiel", "Jeremiah", "Daniel"]),
    correctAnswer: 2,
    explanation: "Jeremiah is traditionally credited as the author of Lamentations, a book mourning the destruction of Jerusalem.",
    bookName: "Lamentations",
    chapter: 1,
    verseNumber: 1,
    category: "general",
    difficulty: "medium",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL BIBLE KNOWLEDGE — HARD
  // ═══════════════════════════════════════════════════════════════════════════
  {
    question: "What is the central chapter of the Bible?",
    optionsJson: JSON.stringify(["Psalm 100", "Psalm 117", "Psalm 119", "Psalm 118"]),
    correctAnswer: 3,
    explanation: "Psalm 118:8-9 are considered the central verses of the Bible. Many translations center the text at Psalm 118.",
    bookName: "Psalms",
    chapter: 118,
    verseNumber: 8,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "Which book of the Bible has the most chapters (besides Psalms)?",
    optionsJson: JSON.stringify(["Isaiah", "Jeremiah", "Ezekiel", "Genesis"]),
    correctAnswer: 1,
    explanation: "Jeremiah has 52 chapters, making it the longest prophetic book and having the most chapters after Psalms.",
    bookName: "Jeremiah",
    chapter: 52,
    verseNumber: 1,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "How many times is the phrase 'fear not' or 'do not be afraid' used in the Bible?",
    optionsJson: JSON.stringify(["365 times", "100 times", "50 times", "200 times"]),
    correctAnswer: 0,
    explanation: "The phrase 'fear not' or 'do not be afraid' appears 365 times in the Bible — one for every day of the year.",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "In which biblical book is there no mention of sin?",
    optionsJson: JSON.stringify(["Ruth", "Esther", "Song of Solomon", "All of the above"]),
    correctAnswer: 3,
    explanation: "Ruth, Esther, and Song of Solomon are the only books of the Bible that do not mention the word 'sin.'",
    category: "general",
    difficulty: "hard",
  },
  {
    question: "Which verse is the exact middle of the Bible?",
    optionsJson: JSON.stringify(["Psalm 118:8", "Psalm 119:1", "Psalm 100:1", "Psalm 23:1"]),
    correctAnswer: 0,
    explanation: "Psalm 118:8 ('It is better to take refuge in the Lord than to trust in man') is considered the middle verse of the Bible.",
    bookName: "Psalms",
    chapter: 118,
    verseNumber: 8,
    category: "general",
    difficulty: "hard",
  },
  {
    question: "What is the only book of the Bible that ends with a question mark?",
    optionsJson: JSON.stringify(["Jonah", "Nahum", "Malachi", "Lamentations"]),
    correctAnswer: 0,
    explanation: "The book of Jonah ends with God's question: 'Should I not have compassion on Nineveh, that great city?' (Jonah 4:11).",
    bookName: "Jonah",
    chapter: 4,
    verseNumber: 11,
    category: "general",
    difficulty: "hard",
  },
];

const main = async () => {
  console.log("Seeding Bible trivia questions...");

  let created = 0;
  let skipped = 0;

  for (const q of questions) {
    try {
      // Build a unique identifier from the question text
      const questionHash = q.question.slice(0, 80);

      const existing = await prisma.triviaQuestion.findFirst({
        where: { question: { startsWith: questionHash } },
      });

      if (existing) {
        console.log(`  ~ Already exists: "${q.question.slice(0, 50)}..."`);
        skipped++;
        continue;
      }

      await prisma.triviaQuestion.create({
        data: {
          question: q.question,
          optionsJson: q.optionsJson,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation || null,
          bookName: q.bookName || null,
          chapter: q.chapter ? BigInt(q.chapter) : null,
          verseNumber: q.verseNumber ? BigInt(q.verseNumber) : null,
          category: q.category || "general",
          difficulty: q.difficulty || "medium",
          isActive: true,
          createdBy: "seed",
        },
      });
      created++;
      console.log(`  ✓ [${q.category}] ${q.question.slice(0, 60)}...`);
    } catch (error) {
      console.error(`  ✗ Error: ${error.message}`);
    }
  }

  console.log(`\nSeeded ${created} new trivia questions (${skipped} skipped, ${questions.length - created - skipped} failed).`);
  console.log(`Total questions in DB: ${await prisma.triviaQuestion.count()}`);
};

main()
  .catch((e) => {
    console.error("Error seeding trivia:", e.message);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
